import type { AppLocale } from "../hooks/usePreferences";

const zh = {
  appTitle: "开始设置",
  sidebarTitle: "设置你的工作环境",
  sidebarHint: "完成后即可开始使用，之后也能在设置中调整。",
  sidebarFootTitle: "你的配置由你掌控",
  sidebarFootHint: "偏好保存在本机。供应商凭据通过 Vela 当前的连接流程配置。",
  steps: ["语言与主题", "工具调用", "迁移 Skills", "添加供应商", "默认模型"],
  optional: "可跳过",
  welcomeKicker: "欢迎使用 Vela",
  welcomeTitle: "把 Vela 调成你的工作方式",
  welcomeHint: "花几分钟设置界面偏好、导入常用 Skills，并连接默认模型。每一步都可以回头修改。",
  welcomeMeta: ["5 个步骤", "Skills 迁移可跳过", "约 3 分钟"],
  welcomeFeatures: [
    { title: "界面偏好", hint: "语言、明暗模式和配色" },
    { title: "开发工作流", hint: "工具调用显示与 Skills" },
    { title: "连接模型", hint: "供应商、默认模型和推理强度" },
  ],
  start: "开始设置",
  previous: "上一步",
  next: "继续",
  finishStep: "完成设置",
  resumeHint: "每一步都会保存，稍后可继续。",
  stepKickers: ["界面偏好", "工具调用显示", "Skills 迁移 · 可选", "连接供应商", "默认模型"],
  preferencesTitle: "先设置界面偏好",
  preferencesHint: "选择你习惯的语言和外观。主题会即时预览。",
  language: "语言",
  languageHint: "后续界面将使用所选语言",
  appearance: "明暗模式",
  appearanceHint: "可跟随系统切换",
  theme: "配色",
  themeHint: "浅色和深色各选一个",
  system: "跟随系统",
  light: "浅色",
  dark: "深色",
  lightThemes: "浅色主题",
  darkThemes: "深色主题",
  toolTitle: "工具调用想怎么显示？",
  toolHint: "选择执行过程在对话里的呈现方式。可以之后随时切换。",
  toolCard: "卡片",
  toolCardHint: "每个工具单独显示，可展开查看详情。",
  toolCompact: "紧凑",
  toolCompactHint: "每个工具一行，多次调用折叠成摘要。",
  readFile: "读取文件",
  editFile: "编辑文件",
  runCommand: "运行命令",
  moreTools: "还有 3 项",
  migrateTitle: "把常用 Skills 带过来",
  migrateHint: "从 Codex 或 Claude Code 选择要迁移的 Skills。原来的文件会保留。",
  foundSkills: "找到的 Skills",
  selectedSkills: (count: number) => `已选 ${count} 个`,
  selectAll: "全选",
  selectNone: "全不选",
  codex: "Codex",
  claude: "Claude Code",
  userScope: "用户",
  projectScope: "当前项目",
  skillNew: "可迁移",
  skillAlreadyPresent: "已存在",
  skillsEmpty: "没有在 Codex 或 Claude Code 中找到 Skill。你可以继续完成设置。",
  skillsLoadError: "无法读取可迁移的 Skill。可以重试或跳过这一步。",
  retry: "重试",
  migrating: "正在迁移…",
  migrateAndContinue: "迁移所选并继续",
  continueWithoutMigration: "不迁移，继续",
  skip: "跳过本步",
  migrationDone: (count: number) => `已迁移 ${count} 个 Skill。`,
  migrationPartial: "部分 Skill 未能迁移；你可以之后在设置里重试。",
  migrationError: "迁移没有完成。请重试，或跳过这一步。",
  migrationNote: "已存在于 Vela 的同名 Skill 会标记出来，迁移前可逐项确认。",
  providerTitle: "连接第一个供应商",
  providerHint: "选择要使用的模型服务。已有连接会保留，你可以直接确认或添加供应商。",
  providerSearch: "搜索供应商",
  providerLoading: "正在读取可用供应商…",
  providerLoadError: "无法读取供应商列表。",
  providerEmpty: "没有找到匹配的供应商。",
  providerConnected: "已连接",
  providerNeedsConnection: "需要连接",
  providerModelCount: (count: number) => `${count} 个可用模型`,
  providerSelectHint: "先选择供应商",
  login: "登录",
  apiKey: "填写密钥",
  customProvider: "自定义接口",
  customProviderAction: "添加自定义接口",
  customProviderClose: "收起自定义接口",
  customProviderHint: "兼容接口与本地模型",
  customProviderTitle: "添加自定义接口",
  providerName: "供应商名称",
  providerNamePlaceholder: "例如 Ollama",
  baseUrl: "接口地址",
  apiType: "接口类型",
  apiKeyField: "API 密钥",
  apiKeyPlaceholder: "已有接口可以留空",
  modelId: "模型 ID",
  modelName: "模型名称",
  modelNamePlaceholder: "可选",
  supportsReasoning: "支持推理强度",
  addProvider: "验证并添加",
  connecting: "正在连接…",
  credentialsHint: "凭据保存在本机，登录流程由 Vela 当前的供应商连接界面处理。",
  connectError: "连接没有完成。请检查信息后重试。",
  providerNeedsModel: "此供应商当前没有可用模型，请完成连接或选择其他供应商。",
  modelTitle: "选一个默认模型",
  modelHint: "新对话会默认使用这个模型。推理强度选项随模型能力变化。",
  defaultModel: "默认模型",
  thinkingLevel: "默认推理强度",
  thinkingHint: "只显示当前模型支持的选项。",
  noModels: "这个供应商还没有可用模型。",
  unavailableModel: "当前默认模型暂不可用",
  thinkingLevels: {
    off: "关闭",
    minimal: "最低",
    low: "低",
    medium: "中",
    high: "高",
    xhigh: "极高",
    max: "最高",
  },
  modelNote: "你可以在对话输入框中按需调整推理强度，也可以之后在设置里更改默认值。",
  saveError: "无法保存默认模型设置。请重试。",
  completeKicker: "设置完成",
  completeTitle: "Vela 已经准备好了",
  completeHint: "你的工作环境已设置完成。之后可以在设置中随时调整。",
  summaryLanguage: "语言",
  summaryTheme: "主题",
  summaryTools: "工具调用",
  summaryProvider: "供应商",
  summaryModel: "默认模型",
  enterApp: "开始使用 Vela",
  savedOnDevice: "保存在本机",
} as const;

type Widen<T> = T extends (...args: never[]) => unknown
  ? T
  : T extends string
    ? string
    : T extends readonly (infer Item)[]
      ? readonly Widen<Item>[]
      : T extends object
        ? { [Key in keyof T]: Widen<T[Key]> }
        : T;

const en: Widen<typeof zh> = {
  appTitle: "Get started",
  sidebarTitle: "Set up your workspace",
  sidebarHint: "Finish setup to start using Vela. You can change these choices later.",
  sidebarFootTitle: "Your setup stays yours",
  sidebarFootHint: "Preferences stay on this device. Provider credentials use Vela’s existing sign-in flow.",
  steps: ["Language & theme", "Tool calls", "Migrate skills", "Add provider", "Default model"],
  optional: "Optional",
  welcomeKicker: "WELCOME TO VELA",
  welcomeTitle: "Make Vela work your way",
  welcomeHint: "Set your interface preferences, bring your Skills, and connect a default model in a few minutes. You can revisit every choice.",
  welcomeMeta: ["5 steps", "Skills migration is optional", "About 3 minutes"],
  welcomeFeatures: [
    { title: "Your interface", hint: "Language, appearance, and colors" },
    { title: "Your workflow", hint: "Tool call display and Skills" },
    { title: "Your model", hint: "Provider, default model, and reasoning" },
  ],
  start: "Start setup",
  previous: "Back",
  next: "Continue",
  finishStep: "Finish setup",
  resumeHint: "Each step is saved as you go. You can pick this up later.",
  stepKickers: ["YOUR INTERFACE", "TOOL CALL DISPLAY", "SKILLS · OPTIONAL", "CONNECT A PROVIDER", "DEFAULT MODEL"],
  preferencesTitle: "Set up your interface",
  preferencesHint: "Choose your language and appearance. Theme changes preview instantly.",
  language: "Language",
  languageHint: "The rest of setup follows this language",
  appearance: "Appearance",
  appearanceHint: "Follow your system setting",
  theme: "Color themes",
  themeHint: "Choose one light and one dark theme",
  system: "System",
  light: "Light",
  dark: "Dark",
  lightThemes: "Light themes",
  darkThemes: "Dark themes",
  toolTitle: "How should tool calls appear?",
  toolHint: "Choose how the work appears in chat. You can change this later.",
  toolCard: "Cards",
  toolCardHint: "Show each tool in its own expandable card.",
  toolCompact: "Compact",
  toolCompactHint: "Use one line per tool and summarize repeated calls.",
  readFile: "Read file",
  editFile: "Edit file",
  runCommand: "Run command",
  moreTools: "3 more",
  migrateTitle: "Bring your Skills with you",
  migrateHint: "Choose Skills to migrate from Codex or Claude Code. Original files stay where they are.",
  foundSkills: "Skills found",
  selectedSkills: (count: number) => `${count} selected`,
  selectAll: "Select all",
  selectNone: "Select none",
  codex: "Codex",
  claude: "Claude Code",
  userScope: "User",
  projectScope: "This project",
  skillNew: "Ready to migrate",
  skillAlreadyPresent: "Already in Vela",
  skillsEmpty: "No Skills found in Codex or Claude Code. Continue with setup when you’re ready.",
  skillsLoadError: "Could not read Skills. Retry or skip this step.",
  retry: "Retry",
  migrating: "Migrating…",
  migrateAndContinue: "Migrate selected and continue",
  continueWithoutMigration: "Continue without migrating",
  skip: "Skip this step",
  migrationDone: (count: number) => `${count} Skills migrated.`,
  migrationPartial: "Some Skills could not be migrated. You can retry later in Settings.",
  migrationError: "Migration did not finish. Retry or skip this step.",
  migrationNote: "Skills with the same name in Vela are marked so you can review them before migrating.",
  providerTitle: "Connect your first provider",
  providerHint: "Choose a model provider. Existing connections stay available; you can keep one or add another.",
  providerSearch: "Search providers",
  providerLoading: "Loading available providers…",
  providerLoadError: "Could not load providers.",
  providerEmpty: "No matching providers.",
  providerConnected: "Connected",
  providerNeedsConnection: "Connect to continue",
  providerModelCount: (count: number) => `${count} available models`,
  providerSelectHint: "Select a provider first",
  login: "Sign in",
  apiKey: "Enter API key",
  customProvider: "Custom API",
  customProviderAction: "Add a custom endpoint",
  customProviderClose: "Close custom endpoint form",
  customProviderHint: "Compatible endpoints and local models",
  customProviderTitle: "Add a custom endpoint",
  providerName: "Provider name",
  providerNamePlaceholder: "For example, Ollama",
  baseUrl: "API URL",
  apiType: "API type",
  apiKeyField: "API key",
  apiKeyPlaceholder: "Leave blank if already configured",
  modelId: "Model ID",
  modelName: "Model name",
  modelNamePlaceholder: "Optional",
  supportsReasoning: "Supports reasoning effort",
  addProvider: "Verify and add",
  connecting: "Connecting…",
  credentialsHint: "Credentials stay on this device. Vela handles sign-in with its existing provider flow.",
  connectError: "Could not connect. Check the details and try again.",
  providerNeedsModel: "This provider has no available models yet. Finish connecting it or choose another provider.",
  modelTitle: "Choose a default model",
  modelHint: "New conversations use this model by default. Reasoning options depend on the model.",
  defaultModel: "Default model",
  thinkingLevel: "Default reasoning effort",
  thinkingHint: "Only levels supported by this model are shown.",
  noModels: "This provider has no available models yet.",
  unavailableModel: "The current default model is unavailable",
  thinkingLevels: {
    off: "Off",
    minimal: "Minimal",
    low: "Low",
    medium: "Medium",
    high: "High",
    xhigh: "Extra high",
    max: "Max",
  },
  modelNote: "Adjust reasoning for a conversation from the composer, or change the default later in Settings.",
  saveError: "Could not save the default model. Try again.",
  completeKicker: "ALL SET",
  completeTitle: "Vela is ready",
  completeHint: "Your workspace is set up. You can change these choices in Settings any time.",
  summaryLanguage: "Language",
  summaryTheme: "Theme",
  summaryTools: "Tool calls",
  summaryProvider: "Provider",
  summaryModel: "Default model",
  enterApp: "Start using Vela",
  savedOnDevice: "Saved on this device",
};

export type OnboardingCopy = Widen<typeof zh>;

export function onboardingCopy(locale: AppLocale): OnboardingCopy {
  return locale === "en" ? en : zh;
}
