import { useState } from 'react';
import { canRetryRecipeStage, compareRecipeRevisions, recipeStageSelected, type RecipeRun, type RecipeStage, type RecipeStageEvidence, type RecipeValue, type TaskRecipeInput, type TaskRecipesState } from '@vela/shared';
import { tr } from '../locale';

export function RecipeStageEditor({ recipe, fields, onChange }: { recipe: TaskRecipeInput; fields: Record<string, string>; onChange: (stages: RecipeStage[]) => void }) {
  const stages = recipe.stages ?? [];
  const change = (i: number, value: RecipeStage) => onChange(stages.map((s, n) => n === i ? value : s));
  return <section className="recipe-stages-editor"><div className="scheduled-task-title"><h3>{tr('结构化阶段', 'Structured stages')} ({stages.length}/20)</h3><button type="button" disabled={stages.length >= 20} onClick={() => onChange([...stages, { id: `stage_${crypto.randomUUID().slice(0, 8)}`, name: '', instructions: '', sideEffect: 'read_only', approvalRequired: false, retryLimit: 0 }])}>{tr('添加阶段', 'Add stage')}</button></div>
    <p className="scheduled-tasks-note">{tr('未添加阶段时沿用单次任务。添加后，Agent 按阶段逐次执行；Plan 只生成整体方案。只读阶段限制工具，不允许修改、浏览器、MCP 或子任务。完成表示该阶段回复结束，验收由你评价。', 'Without stages, the recipe runs once. Agent runs stages in order; Plan produces one proposal. Read-only stages block writes, browser, MCP, and child tasks. Completion means the stage response ended; you assess acceptance.')}</p>
    {fields.stages && <p role="alert" className="recipe-errors">{fields.stages}</p>}
    {stages.map((stage, i) => {
      const set = <K extends keyof RecipeStage>(key: K, value: RecipeStage[K]) => change(i, { ...stage, [key]: value });
      const error = (field: string) => fields[`stages.${i}.${field}`];
      const invalid = (field: string) => ({ 'aria-invalid': !!error(field) });
      const errorNode = (field: string) => error(field) && <span role="alert" className="recipe-errors">{error(field)}</span>;
      const conditionParameter = recipe.parameters.find(p => p.id === stage.condition?.parameterId);
      return <fieldset key={i} className="recipe-parameter"><legend>{tr('阶段', 'Stage')} {i + 1}</legend>
        <div className="recipe-columns"><label>{tr('阶段标识', 'Stage identifier')}<input {...invalid('id')} value={stage.id} onChange={e => set('id', e.target.value)} />{errorNode('id')}</label><label>{tr('阶段名称', 'Stage name')}<input {...invalid('name')} value={stage.name} maxLength={80} onChange={e => set('name', e.target.value)} />{errorNode('name')}</label></div>
        <label>{tr('阶段要求', 'Stage instructions')}<textarea {...invalid('instructions')} value={stage.instructions} rows={3} onChange={e => set('instructions', e.target.value)} />{errorNode('instructions')}</label>
        <div className="recipe-columns"><label>{tr('副作用范围', 'Effect boundary')}<select {...invalid('sideEffect')} value={stage.sideEffect} onChange={e => change(i, { ...stage, sideEffect: e.target.value as RecipeStage['sideEffect'], retryLimit: 0 })}><option value="read_only">{tr('只读查阅', 'Read only')}</option><option value="workspace">{tr('可能修改工作区', 'May change workspace')}</option><option value="external">{tr('可能操作外部服务', 'May affect external services')}</option></select>{errorNode('sideEffect')}</label>
          <label>{tr('手动重试上限', 'Manual retry limit')}<select {...invalid('retryLimit')} value={stage.retryLimit} disabled={stage.sideEffect !== 'read_only'} onChange={e => set('retryLimit', Number(e.target.value))}>{[0, 1, 2, 3].map(n => <option key={n} value={n}>{n}</option>)}</select>{errorNode('retryLimit')}</label></div>
        <p className="scheduled-tasks-note">{tr('副作用范围是配方声明；工作区与外部阶段仍使用原工具权限。只有已确认失败的只读阶段允许手动重试，结果不明或中断均不重放。', 'Effect scope is declared by the template; existing tool permissions apply. Only confirmed failures in read-only stages can be retried manually. Interrupted or uncertain results are never replayed.')}</p>
        <label className="recipe-checkbox"><input type="checkbox" checked={stage.approvalRequired} onChange={e => set('approvalRequired', e.target.checked)} />{tr('进入此阶段前需要审批', 'Require approval before entering this stage')}</label>
        <label>{tr('执行条件', 'Run condition')}<select {...invalid('condition')} value={stage.condition?.parameterId ?? ''} onChange={e => { const p = recipe.parameters.find(p => p.id === e.target.value); set('condition', p ? { parameterId: p.id, operator: 'equals', value: p.type === 'boolean' ? true : p.type === 'select' ? p.options?.[0]?.value ?? '' : '' } : undefined); }}><option value="">{tr('始终执行', 'Always run')}</option>{recipe.parameters.map(p => <option key={p.id} value={p.id}>{p.label || p.id}</option>)}</select>{errorNode('condition')}</label>
        {stage.condition && <div className="recipe-columns"><label>{tr('比较方式', 'Comparison')}<select value={stage.condition.operator} onChange={e => set('condition', { ...stage.condition!, operator: e.target.value as 'equals' | 'not_equals' })}><option value="equals">{tr('等于', 'Equals')}</option><option value="not_equals">{tr('不等于', 'Does not equal')}</option></select></label>
          <label>{tr('比较值', 'Compare with')}{conditionParameter?.type === 'boolean' ? <select value={String(stage.condition.value)} onChange={e => set('condition', { ...stage.condition!, value: e.target.value === 'true' })}><option value="true">{tr('是', 'Yes')}</option><option value="false">{tr('否', 'No')}</option></select> : conditionParameter?.type === 'select' ? <select value={String(stage.condition.value)} onChange={e => set('condition', { ...stage.condition!, value: e.target.value })}>{conditionParameter.options?.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select> : <input value={String(stage.condition.value)} onChange={e => set('condition', { ...stage.condition!, value: e.target.value })} />}</label></div>}
        <div className="scheduled-task-actions"><button type="button" disabled={i === 0} onClick={() => { const next = [...stages]; [next[i - 1], next[i]] = [next[i]!, next[i - 1]!]; onChange(next); }}>{tr('上移', 'Move up')}</button><button type="button" disabled={i === stages.length - 1} onClick={() => { const next = [...stages]; [next[i], next[i + 1]] = [next[i + 1]!, next[i]!]; onChange(next); }}>{tr('下移', 'Move down')}</button><button type="button" onClick={() => onChange(stages.filter((_, n) => n !== i))}>{tr('移除阶段', 'Remove stage')}</button></div>
      </fieldset>;
    })}
  </section>;
}
export function RecipeStagePreview({ recipe, values, mode }: { recipe: TaskRecipeInput; values: Record<string, RecipeValue>; mode: string }) {
  if (!recipe.stages?.length) return null;
  return <section className="recipe-stage-preview"><h3>{tr('本次阶段', 'Stages for this run')}</h3>{mode === 'plan' && <p>{tr('Plan 只规划这些阶段，不启动阶段执行或自动批准。', 'Plan proposes these stages without executing or approving them.')}</p>}<ol>{recipe.stages.map(stage => <li key={stage.id}>{stage.name} · {recipeStageSelected(stage, values) ? tr('执行', 'Selected') : tr('条件不匹配，跳过', 'Condition not met; skip')} · {stage.sideEffect}{stage.approvalRequired ? ` · ${tr('进入前审批', 'Approval before entry')}` : ''}</li>)}</ol></section>;
}
const stageStatus = (value: string) => ({ pending: tr('待执行', 'Pending'), skipped: tr('已跳过', 'Skipped'), waiting_for_approval: tr('待审批', 'Awaiting approval'), running: tr('执行中', 'Running'), responded: tr('阶段回复已生成', 'Stage response generated'), failed: tr('失败', 'Failed'), stopped: tr('已停止', 'Stopped'), interrupted: tr('已中断', 'Interrupted') })[value as 'pending'];
export function RecipeRunProgress({ run }: { run: RecipeRun }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [evidence, setEvidence] = useState<{ label: string; text: string } | null>(null);
  const act = async (action: () => Promise<unknown>) => { setBusy(true); setError(''); try { await action(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const showEvidence = async (item: RecipeStageEvidence, stageId: string, attempt: number) => {
    setEvidence(await window.vela!.taskRecipes!.stageEvidence(run.id, stageId, attempt, item.id));
  };
  if (!run.stages) return null;
  const terminal = !['starting', 'running', 'waiting_for_user'].includes(run.status);
  return <section className="recipe-run-progress" aria-label={tr('阶段进度', 'Stage progress')}><p role="status">{tr('阶段回复', 'Stage responses')}: {run.stages.filter(s => s.status === 'responded').length}/{run.stages.filter(s => s.status !== 'skipped').length}</p><ol>{run.stages.map(stage => {
    const definition = run.recipeSnapshot.stages!.find(s => s.id === stage.stageId)!;
    return <li key={stage.stageId}><strong>{definition.name}</strong><span> · {stageStatus(stage.status)}</span>
      {stage.status === 'waiting_for_approval' && <div className="scheduled-task-actions"><button type="button" disabled={busy} onClick={() => void act(() => window.vela!.taskRecipes!.approveStage(run.id, stage.stageId, true))}>{tr('批准阶段', 'Approve stage')}</button><button type="button" disabled={busy} onClick={() => void act(() => window.vela!.taskRecipes!.approveStage(run.id, stage.stageId, false))}>{tr('拒绝并停止', 'Reject and stop')}</button></div>}
      {canRetryRecipeStage(run, stage.stageId) && run.trigger !== 'scheduled' && <button type="button" disabled={busy} onClick={() => void act(() => window.vela!.taskRecipes!.retryStage(run.id, stage.stageId, crypto.randomUUID()))}>{tr('重试此只读阶段', 'Retry this read-only stage')} ({stage.attempts.length}/{definition.retryLimit + 1})</button>}
      {terminal && stage.status === 'failed' && !canRetryRecipeStage(run, stage.stageId) && <p className="scheduled-tasks-note">{tr('此阶段不能原地重试。检查已发生的操作，再通过快照新建任务。', 'This stage cannot be retried in place. Inspect its effects before creating another run from the snapshot.')}</p>}
      {stage.attempts.map(attempt => <details key={attempt.attempt}><summary>{tr('尝试', 'Attempt')} {attempt.attempt} · {stageStatus(attempt.status)} · {attempt.finishedAt === null ? '…' : `${Math.max(0, attempt.finishedAt - attempt.startedAt) / 1000}s`}</summary>{attempt.error && <p className="recipe-errors">{attempt.error}</p>}<ul>{attempt.evidence.map(item => <li key={`${item.type}:${item.id}`}><button type="button" disabled={busy} onClick={() => void act(() => showEvidence(item, stage.stageId, attempt.attempt))}>{item.label}</button><code>{item.id}</code></li>)}</ul>{attempt.evidence.length === 0 && <p>{tr('尚无已确认的证据。', 'No confirmed evidence yet.')}</p>}</details>)}
    </li>;
  })}</ol>{busy && <p role="status">{tr('处理中…', 'Working…')}</p>}{error && <p role="alert" className="recipe-errors">{error}</p>}{evidence && <div><strong>{evidence.label}</strong><button type="button" onClick={() => setEvidence(null)}>{tr('关闭证据', 'Close evidence')}</button><pre className="recipe-preview">{evidence.text}</pre></div>}<p className="scheduled-tasks-note">{tr('阶段回复结束不代表验收通过。状态依据运行时回合事件，证据引用实际聊天记录。', 'Stage response completion does not mean acceptance. Status follows runtime turn events; evidence links to actual chat records.')}</p></section>;
}
export function RecipeRunOutcome({ run }: { run: RecipeRun }) {
  const [rating, setRating] = useState<'accepted' | 'needs_work'>(run.outcome?.rating ?? 'accepted'); const [note, setNote] = useState(run.outcome?.note ?? '');
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  if (['starting', 'running', 'waiting_for_user'].includes(run.status)) return null;
  return <details className="recipe-run-outcome"><summary>{tr('评价本次效果', 'Assess this run')}{run.outcome ? ` · ${run.outcome.rating === 'accepted' ? tr('已验收', 'Accepted') : tr('需改进', 'Needs work')}` : ` · ${tr('未评价', 'Not rated')}`}</summary><label>{tr('你的评价', 'Your assessment')}<select value={rating} onChange={e => setRating(e.target.value as typeof rating)}><option value="accepted">{tr('已验收', 'Accepted')}</option><option value="needs_work">{tr('需改进', 'Needs work')}</option></select></label><label>{tr('评价说明（仅本机保存）', 'Notes (saved locally)')}<textarea rows={2} maxLength={2000} value={note} onChange={e => setNote(e.target.value)} /></label><button type="button" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { await window.vela!.taskRecipes!.rateRun(run.id, rating, note); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}>{busy ? tr('保存中…', 'Saving…') : tr('保存评价', 'Save assessment')}</button>{error && <p role="alert" className="recipe-errors">{error}</p>}</details>;
}
export function RecipeComparison({ runs }: { runs: RecipeRun[] }) {
  const rows = compareRecipeRevisions(runs);
  if (!rows.length) return null;
  return <details className="recipe-comparison"><summary>{tr('比较版本效果', 'Compare revision outcomes')}</summary><p className="scheduled-tasks-note">{tr('仅统计本机记录，参数、聊天内容和评价不写入团队库。回复生成数表示运行时结束；验收数仅来自用户评价。耗时含等待审批与重试间隔，工作区与模型差异可能影响比较。', 'Only local records are compared. Parameters, chats, and assessments are not shared. Responses count runtime completion; acceptance comes only from user ratings. Duration includes approval and retry waits. Workspace and model differences can affect comparisons.')}</p><div className="recipe-table-scroll"><table><thead><tr>{[tr('配方版本', 'Recipe revision'), tr('次数', 'Runs'), tr('回复生成', 'Responses'), tr('失败／停止／中断', 'Failed/stopped/interrupted'), tr('验收／需改进／已评价', 'Accepted/needs work/rated'), tr('平均耗时', 'Mean duration')].map(title => <th key={title} scope="col">{title}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={`${row.recipeId}:${row.revision}`}><th scope="row">{row.name} · r{row.revision}<small>{row.recipeId}</small></th><td>{row.runs}</td><td>{row.responded}</td><td>{row.failed}/{row.stopped}/{row.interrupted}</td><td>{row.accepted}/{row.needsWork}/{row.rated}</td><td>{row.averageDurationMs === null ? '—' : `${Math.round(row.averageDurationMs / 1000)}s`}</td></tr>)}</tbody></table></div></details>;
}
export function RecipeTeamPanel({ state, workspaces }: { state: TaskRecipesState; workspaces: string[] }) {
  const [workspace, setWorkspace] = useState(workspaces[0] ?? ''); const [permission, setPermission] = useState<'read' | 'write'>('read'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const act = async (action: () => Promise<unknown>) => { setBusy(true); setError(''); try { await action(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  return <details className="recipe-team-panel"><summary>{tr('团队配方库', 'Team recipe libraries')} ({state.teams?.length ?? 0})</summary><p>{tr('团队模板保存到项目的 .vela/team-task-recipes.json，可通过 Git 或共享目录同步。实际访问权限由仓库或文件系统控制；这里的写入开关只限制本机操作。仅共享模板，参数默认值与正文会共享，请勿填写凭据。运行参数、记录、评价与来源聊天不会共享。', 'Templates live in .vela/team-task-recipes.json and can be shared through Git or a shared folder. Repository/filesystem permissions control access; the write setting controls this client only. Template text and parameter defaults are shared; do not include credentials. Run inputs, history, assessments, and source chat references stay local.')}</p>
    <div className="recipe-columns"><label>{tr('团队项目', 'Team project')}<select disabled={busy} value={workspace} onChange={e => setWorkspace(e.target.value)}><option value="">{tr('选择工作区', 'Choose workspace')}</option>{workspaces.map(w => <option key={w} value={w}>{w}</option>)}</select></label><label>{tr('本机共享权限', 'Local library permission')}<select disabled={busy} value={permission} onChange={e => setPermission(e.target.value as typeof permission)}><option value="read">{tr('只读', 'Read only')}</option><option value="write">{tr('允许写入共享模板', 'Allow writing shared templates')}</option></select></label></div><button type="button" disabled={busy || !workspace} onClick={() => void act(() => window.vela!.taskRecipes!.connectTeam(workspace, permission))}>{tr('连接／更新权限', 'Connect/update permission')}</button>
    {(state.teams ?? []).map(team => <div key={team.workspace} className="scheduled-task-actions"><span className="scheduled-task-path">{team.workspace} · {team.permission === 'read' ? tr('只读', 'Read only') : tr('可写', 'Writable')}</span><button type="button" disabled={busy} onClick={() => void act(() => window.vela!.taskRecipes!.disconnectTeam(team.workspace))}>{tr('断开本机连接', 'Disconnect locally')}</button></div>)}{Object.entries(state.teamErrors ?? {}).map(([path, message]) => <p key={path} role="alert" className="recipe-errors">{path}: {message}</p>)}{error && <p role="alert" className="recipe-errors">{error}</p>}</details>;
}
