import type { AppLocale } from "../hooks/usePreferences";

const zh = {
  title: "设置",
  done: "完成",
  open: "设置",
  nav: {
    agent: "Agent",
    archived: "对话归档",
    models: "模型与账号",
    permissions: "执行权限",
    workspace: "工作区",
    appearance: "外观与快捷键",
  },
  archived: {
    title: "已归档对话",
    hint: "归档的对话不在侧边栏显示,历史仍然保留。在这里搜索后取消归档即可恢复。",
    searchPlaceholder: "搜索标题或工作区",
    empty: "还没有归档的对话。把鼠标悬停在侧边栏的会话上即可归档。",
    searchEmpty: "没有符合条件的归档对话。",
    workspace: "工作区",
    unarchive: "取消归档",
    unarchived: "对话已恢复到侧边栏",
  },
  agent: {
    model: "默认模型",
    modelHint: "新对话默认使用此模型。你也可以在输入框中为当前对话切换模型。",
    modelEmpty: "未选择",
    modelMissing: "还没有可用模型。先在「模型与账号」里登录或添加。",
    modelUnavailable: "当前默认模型还不能使用",
    thinking: "默认思考强度",
    thinkingHint: "模型可能不支持所有思考强度，可选项会根据当前模型调整。",
    levels: {
      off: "关闭",
      minimal: "最低",
      low: "低",
      medium: "中",
      high: "高",
      xhigh: "极高",
      max: "最高",
    },
    newConversation: "新对话使用的选择",
    newConversationHint: "「设置默认」让新对话使用上面的默认模型和思考强度；「上次使用」沿用最近一次在对话里用过的模型和思考强度，那个模型不可用时回退到默认。",
    newConversationDefault: "设置默认",
    newConversationLastUsed: "上次使用",
    instructions: "额外指令",
    instructionsHint: "为 Agent 补充长期遵循的偏好，仅对新建对话生效。",
    instructionsPlaceholder: "例如：请优先用简洁的中文回答；修改代码前先阅读相关文件；不确定时先说明你的假设。",
    skills: "Skills",
    skillsHint: "把包含 SKILL.md 的目录放在下方路径。新对话会按名称和描述决定是否读取全文。在输入框输入 / 可以选择 Skill，也可以直接发送 /skill:名称。每个 Skill 都能单独停用；Vela 目录里的 Skill 还可以删除。",
    skillsEmpty: "还没有 Skill。",
    openSkills: "打开 Skill 目录",
    skillsLoadError: "无法读取 Skill",
    skillCommandOnly: "仅命令",
    skillOrigins: {
      user: "用户",
      project: "项目",
      agents: "~/.agents",
    },
    skillEnabled: "已启用",
    skillDisabled: "已停用",
    skillDisable: "停用",
    skillEnable: "启用",
    skillDelete: "删除",
    skillDeleteConfirm: "确认删除",
    skillToggleHint: "停用后新对话不再加载这个 Skill，也不能用 /skill:名称 调用；已打开的对话会在下次发送前刷新。",
    skillDeleteHint: "从 Vela Skill 目录删除文件，无法撤销。",
    skillDeleteNote: "项目、~/.agents 等目录里的 Skill 只能停用；要删除请到对应目录操作。",
    migrate: "从 Codex / Claude Code 迁移",
    migrateTitle: "选择要迁移的 Skill",
    migrateHint: "勾选要复制到 Vela 的 Skill。新的 Skill 已预先勾选。原来的文件会保留；勾选已存在的同名 Skill 会覆盖。",
    migrateEmpty: "没有在 Codex 或 Claude Code 中找到 Skill。",
    migrateLoadError: "无法读取可迁移的 Skill",
    migrateSources: {
      codex: "Codex",
      claude: "Claude Code",
    },
    migrateScopes: {
      user: "用户",
      project: "当前项目",
    },
    migrateStates: {
      present: "已存在",
      loaded: "已加载",
    },
    migrateReplaceNote: "勾选后覆盖 Vela 中的同名 Skill",
    migrateLoadedNote: "Vela 已从原位置加载",
    migrateLocalNote: "已经在 Vela 的 Skill 目录里",
    migrateSameName: "与前面的选项同名，只会迁移第一个",
    migrateSelectAll: "全选",
    migrateSelectNone: "全不选",
    migrateSelected: (count: number) => `已选 ${count} 个`,
    migrateConfirm: "迁移所选",
    migrating: "正在迁移",
    migrateCancel: "取消",
    migrateClose: "关闭",
    migrateLoading: "正在查找 Skill",
    migrateDone: (count: number) => `已迁移 ${count} 个 Skill`,
    migrateNone: "没有迁移任何 Skill",
    migrateSkip: {
      "not-found": "找不到这个 Skill",
      unsafe: "这个 Skill 不在可迁移的目录里",
      "already-local": "已经在 Vela 的 Skill 目录里",
      duplicate: "与其他所选 Skill 同名，已跳过",
      failed: "复制失败",
    },
    restore: "恢复默认",
    save: "保存设置",
    saving: "正在保存",
    saved: "已保存",
    loadError: "无法读取 Agent 设置",
  },
  models: {
    connected: "已连接的提供方",
    empty: "还没有提供方。可以在下方添加自定义模型。",
    connectedStatus: "已连接",
    disconnectedStatus: "未连接",
    modelCount: (count: number) => `${count} 个可用模型`,
    visibility: "输入框中的模型",
    visibilityHint: "取消勾选后，该模型不会出现在主页输入框的模型列表里，随时可以重新勾选。当前正在使用的模型仍会显示，方便切换。",
    visibilityEmpty: "还没有可用模型。先登录提供方或添加模型，再选择显示哪些。",
    visibilityHidden: "已隐藏",
    visibilityShow: "在输入框中显示",
    visibilityHide: "在输入框中隐藏",
    visibilityShowAll: (count: number) => `全部显示（已隐藏 ${count} 个）`,
    login: "登录",
    apiKey: "填写密钥",
    logout: "退出登录",
    remove: "移除",
    confirmRemove: "确认移除",
    add: "添加自定义模型",
    providerName: "提供方名称",
    providerPlaceholder: "例如 Ollama",
    baseUrl: "接口地址",
    baseUrlPlaceholder: "http://127.0.0.1:11434/v1",
    api: "接口类型",
    apiKeyField: "API 密钥",
    apiKeyPlaceholder: "已有接口可以留空",
    modelId: "模型 ID",
    modelIdPlaceholder: "qwen2.5-coder:7b",
    displayName: "显示名称",
    displayNamePlaceholder: "在列表中显示的名称",
    optional: "可选",
    reasoning: "支持推理",
    context: "上下文长度",
    maxOutput: "最大输出长度",
    optionalPlaceholder: "可选",
    submit: "测试并添加模型",
    submitting: "正在测试",
    added: "已添加",
    keyHint: "API 密钥会保存在本机，用于连接该模型提供方。",
    providerInvalid: "需要填写提供方名称。",
    apis: {
      "openai-completions": "OpenAI Chat Completions",
      "openai-responses": "OpenAI Responses",
      "anthropic-messages": "Anthropic Messages",
      "google-generative-ai": "Google Generative AI",
    },
  },
  permissions: {
    ask: "每次询问",
    askHint: "运行终端命令前需要你逐次批准。修改工作区外的文件前也需要批准；工作区内的文件修改无需逐次确认。",
    smart: "帮我批准",
    smartHint: "先由当前对话选择的模型判断风险。只有风险操作或判断失败时才需要你批准，低风险操作直接执行。",
    full: "完全访问",
    fullHint: "在当前工具权限范围内执行命令和文件修改，不再逐项询问。",
    note: "执行权限会影响 Agent 能自动完成的操作。你可以随时在输入框旁切换。",
  },
  workspace: {
    current: "当前工作区",
    empty: "尚未选择工作区",
    choose: "选择文件夹",
    close: "关闭工作区",
    recent: "最近使用",
    recentEmpty: "还没有最近使用的文件夹。",
    removeRecent: "从最近使用中移除",
    environment: "执行环境",
    local: "本地",
    localHint: "直接在当前工作区中操作。",
    worktree: "工作树",
    worktreeHint: "使用独立的 Git worktree 操作，适合隔离代码改动。",
    sandbox: "沙箱",
    remote: "远程",
    soon: "即将支持",
    switching: "切换中",
  },
  appearance: {
    theme: "外观",
    system: "跟随系统",
    light: "浅色",
    dark: "深色",
    palette: "主题",
    paletteHint: "浅色和深色各选一个主题。跟随系统时，会随系统外观在两者之间切换。",
    lightThemes: "浅色主题",
    darkThemes: "深色主题",
    inUse: "使用中",
    themes: {
      daylight: { name: "晴空", hint: "冷白底色，湛蓝点缀" },
      paper: { name: "宣纸", hint: "温润米色，赤陶点缀" },
      celadon: { name: "青瓷", hint: "淡青釉色，松石绿点缀" },
      midnight: { name: "夜航", hint: "深蓝夜色，冷静专注" },
      graphite: { name: "石墨", hint: "中性近黑，薰衣草紫点缀" },
      ember: { name: "余烬", hint: "暖炭底色，余火橙点缀" },
    },
    language: "语言",
    zh: "简体中文",
    en: "English",
    toolDisplay: "工具调用显示",
    toolDisplayHint: "「卡片」为每个工具显示可展开的卡片；「紧凑」每个工具一行，调用超过一次时自动折叠成摘要，点击文件名可在右侧预览。",
    toolCard: "卡片",
    toolCompact: "紧凑",
    toolFold: "工具折叠方式",
    toolFoldHint: "「按 Assistant 消息」只合并同一条消息里的连续工具；「按位置关系」允许相邻消息的工具合并成一组，思考、正文、用户消息和交互卡片仍会打断分组。",
    toolFoldMessage: "按 Assistant 消息",
    toolFoldPosition: "按位置关系",
    fileIconTheme: "文件图标",
    fileIconThemeHint: "选择文件预览和工具调用中使用的图标样式。",
    devicon: "Devicon",
    materialIconTheme: "Material Icon Theme",
    shortcuts: "快捷键",
    shortcutsHint: "这些是当前可用的快捷键。",
    items: {
      sidebar: "折叠侧边栏",
      panel: "折叠右侧面板",
      settings: "打开设置",
      close: "关闭设置或对话框",
      send: "发送消息",
      newline: "换行",
    },
  },
};

const en: typeof zh = {
  title: "Settings",
  done: "Done",
  open: "Settings",
  nav: {
    agent: "Agent",
    archived: "Archived chats",
    models: "Models & accounts",
    permissions: "Execution permissions",
    workspace: "Workspace",
    appearance: "Appearance & shortcuts",
  },
  archived: {
    title: "Archived conversations",
    hint: "Archived conversations are hidden from the sidebar but keep their history. Search here and unarchive to restore.",
    searchPlaceholder: "Search titles or workspaces",
    empty: "No archived conversations yet. Hover a chat in the sidebar to archive it.",
    searchEmpty: "No archived conversations match.",
    workspace: "Workspace",
    unarchive: "Unarchive",
    unarchived: "Conversation restored to the sidebar",
  },
  agent: {
    model: "Default model",
    modelHint: "New conversations use this model. You can still switch the model for the current conversation from the input.",
    modelEmpty: "None selected",
    modelMissing: "No models are available yet. Log in or add one under Models & accounts.",
    modelUnavailable: "The current default model is not available",
    thinking: "Default thinking level",
    thinkingHint: "A model may not support every level. The choices follow the selected model.",
    levels: {
      off: "Off",
      minimal: "Minimal",
      low: "Low",
      medium: "Medium",
      high: "High",
      xhigh: "Extra high",
      max: "Max",
    },
    newConversation: "What new conversations start with",
    newConversationHint: "“Settings default” starts new conversations with the default model and reasoning effort above. “Last used” reuses the model and reasoning effort from your most recent conversation, falling back to the default when that model is unavailable.",
    newConversationDefault: "Settings default",
    newConversationLastUsed: "Last used",
    instructions: "Extra instructions",
    instructionsHint: "Long-term preferences for the agent. They apply only to new conversations.",
    instructionsPlaceholder: "For example: answer in concise English; read the relevant files before editing code; state your assumptions when you are unsure.",
    skills: "Skills",
    skillsHint: "Place a directory containing SKILL.md at the path below. New conversations see each skill’s name and description, then read the full file when it applies. Type / in the composer to choose a skill, or send /skill:name. Each skill can be disabled on its own; skills in Vela’s folder can also be deleted.",
    skillsEmpty: "No skills yet.",
    openSkills: "Open skills folder",
    skillsLoadError: "Could not load skills",
    skillCommandOnly: "Command only",
    skillOrigins: {
      user: "User",
      project: "Project",
      agents: "~/.agents",
    },
    skillEnabled: "Enabled",
    skillDisabled: "Disabled",
    skillDisable: "Disable",
    skillEnable: "Enable",
    skillDelete: "Delete",
    skillDeleteConfirm: "Confirm delete",
    skillToggleHint: "Disabled skills are not loaded into new conversations and cannot be invoked with /skill:name. Open conversations refresh before the next message.",
    skillDeleteHint: "Deletes the files from Vela’s skills folder. This cannot be undone.",
    skillDeleteNote: "Skills from project or ~/.agents folders can only be disabled here. Delete them in their own folder.",
    migrate: "Migrate from Codex / Claude Code",
    migrateTitle: "Choose skills to migrate",
    migrateHint: "Choose which skills to copy into Vela. New skills start selected. The originals stay where they are; selecting an existing skill replaces that copy.",
    migrateEmpty: "No skills were found in Codex or Claude Code.",
    migrateLoadError: "Could not read skills to migrate",
    migrateSources: {
      codex: "Codex",
      claude: "Claude Code",
    },
    migrateScopes: {
      user: "User",
      project: "Current project",
    },
    migrateStates: {
      present: "Already exists",
      loaded: "Already loaded",
    },
    migrateReplaceNote: "Selecting this replaces the Vela copy",
    migrateLoadedNote: "Vela already loads this from its current location",
    migrateLocalNote: "Already in Vela’s skills folder",
    migrateSameName: "Same folder as an earlier choice; only the first one is migrated",
    migrateSelectAll: "Select all",
    migrateSelectNone: "Clear",
    migrateSelected: (count: number) => `${count} selected`,
    migrateConfirm: "Migrate selected",
    migrating: "Migrating",
    migrateCancel: "Cancel",
    migrateClose: "Close",
    migrateLoading: "Looking for skills",
    migrateDone: (count: number) => `Migrated ${count} ${count === 1 ? "skill" : "skills"}`,
    migrateNone: "No skills were migrated",
    migrateSkip: {
      "not-found": "This skill could not be found",
      unsafe: "This skill is outside the folders that can be migrated",
      "already-local": "Already in Vela’s skills folder",
      duplicate: "Skipped because another selected skill uses the same folder",
      failed: "Could not copy this skill",
    },
    restore: "Restore defaults",
    save: "Save settings",
    saving: "Saving",
    saved: "Saved",
    loadError: "Could not load agent settings",
  },
  models: {
    connected: "Connected providers",
    empty: "No providers yet. Add a custom model below.",
    connectedStatus: "Connected",
    disconnectedStatus: "Not connected",
    modelCount: (count: number) => `${count} available ${count === 1 ? "model" : "models"}`,
    visibility: "Models in the composer",
    visibilityHint: "Uncheck a model to keep it out of the model list in the home composer. You can check it again at any time. The model currently in use still appears so you can switch away.",
    visibilityEmpty: "No models are available yet. Sign in to a provider or add a model, then choose which ones to show.",
    visibilityHidden: "Hidden",
    visibilityShow: "Show in the composer",
    visibilityHide: "Hide from the composer",
    visibilityShowAll: (count: number) => `Show all (${count} hidden)`,
    login: "Log in",
    apiKey: "Enter API key",
    logout: "Log out",
    remove: "Remove",
    confirmRemove: "Confirm remove",
    add: "Add a custom model",
    providerName: "Provider name",
    providerPlaceholder: "For example, Ollama",
    baseUrl: "Endpoint",
    baseUrlPlaceholder: "http://127.0.0.1:11434/v1",
    api: "API type",
    apiKeyField: "API key",
    apiKeyPlaceholder: "Leave blank if this endpoint already has a key",
    modelId: "Model ID",
    modelIdPlaceholder: "qwen2.5-coder:7b",
    displayName: "Display name",
    displayNamePlaceholder: "Name shown in the model list",
    optional: "Optional",
    reasoning: "Supports reasoning",
    context: "Context length",
    maxOutput: "Max output length",
    optionalPlaceholder: "Optional",
    submit: "Test and add model",
    submitting: "Testing",
    added: "Added",
    keyHint: "The API key stays on this Mac and is used to reach that provider.",
    providerInvalid: "Enter a provider name.",
    apis: {
      "openai-completions": "OpenAI Chat Completions",
      "openai-responses": "OpenAI Responses",
      "anthropic-messages": "Anthropic Messages",
      "google-generative-ai": "Google Generative AI",
    },
  },
  permissions: {
    ask: "Ask every time",
    askHint: "Each terminal command needs your approval. Changes outside the workspace also need approval; edits inside the workspace do not.",
    smart: "Smart approval",
    smartHint: "The model selected for the current conversation checks each action first. Only risky actions, or when the check fails, need your approval; low-risk actions run directly.",
    full: "Full access",
    fullHint: "Run commands and edit files within the current tool permissions without asking each time.",
    note: "Execution permissions change what the agent can do on its own. You can switch them beside the input at any time.",
  },
  workspace: {
    current: "Current workspace",
    empty: "No workspace selected",
    choose: "Choose folder",
    close: "Close workspace",
    recent: "Recent",
    recentEmpty: "No recent folders yet.",
    removeRecent: "Remove from recent",
    environment: "Execution environment",
    local: "Local",
    localHint: "Work directly in the current workspace.",
    worktree: "Worktree",
    worktreeHint: "Use a separate Git worktree, so code changes stay isolated.",
    sandbox: "Sandbox",
    remote: "Remote",
    soon: "Coming soon",
    switching: "Switching",
  },
  appearance: {
    theme: "Appearance",
    system: "System",
    light: "Light",
    dark: "Dark",
    palette: "Theme",
    paletteHint: "Pick one light and one dark theme. With System, Vela switches between them as your OS appearance changes.",
    lightThemes: "Light themes",
    darkThemes: "Dark themes",
    inUse: "In use",
    themes: {
      daylight: { name: "Daylight", hint: "Crisp white with clear blue" },
      paper: { name: "Paper", hint: "Warm cream with terracotta" },
      celadon: { name: "Celadon", hint: "Pale jade glaze with teal" },
      midnight: { name: "Midnight", hint: "Deep navy for calm focus" },
      graphite: { name: "Graphite", hint: "Neutral near-black with lavender" },
      ember: { name: "Ember", hint: "Warm charcoal with glowing orange" },
    },
    language: "Language",
    zh: "简体中文",
    en: "English",
    toolDisplay: "Tool call display",
    toolDisplayHint: "“Cards” show one expandable card per tool call. “Compact” shows one line per tool, collapsing into a summary after multiple calls; click a file name to preview it on the right.",
    toolCard: "Cards",
    toolCompact: "Compact",
    toolFold: "Tool grouping",
    toolFoldHint: "“By assistant message” merges consecutive calls inside one message. “By position” also merges calls from adjacent messages; thinking, visible text, user messages, and interactive cards still break the grouping.",
    toolFoldMessage: "By assistant message",
    toolFoldPosition: "By position",
    fileIconTheme: "File icons",
    fileIconThemeHint: "Choose the icon style used in file previews and tool calls.",
    devicon: "Devicon",
    materialIconTheme: "Material Icon Theme",
    shortcuts: "Shortcuts",
    shortcutsHint: "These shortcuts work today.",
    items: {
      sidebar: "Toggle sidebar",
      panel: "Toggle the right panel",
      settings: "Open settings",
      close: "Close settings or dialog",
      send: "Send message",
      newline: "New line",
    },
  },
};

export type SettingsCopy = typeof zh;

export function settingsCopy(locale: AppLocale): SettingsCopy {
  return locale === "en" ? en : zh;
}
