import { localizeCopy, type UpdateErrorCode } from "@vela/shared";
import type { AppLocale } from "../hooks/usePreferences";

const zh = {
  title: "设置",
  done: "完成",
  open: "设置",
  groups: {
    general: "通用",
    agent: "Agent",
    extensions: "模型与扩展",
    data: "数据与工作区",
    development: "开发",
  },
  pages: {
    appearance: { label: "外观", description: "主题、配色和文件图标。" },
    interface: { label: "界面", description: "语言、布局、侧边栏、输入框和提示音。" },
    shortcuts: { label: "快捷键", description: "当前可用的快捷键。" },
    updates: { label: "关于与更新", description: "当前版本、检查更新和自动更新。" },
    defaults: { label: "默认与权限", description: "新对话的默认模型、思考强度、额外指令和执行权限。" },
    display: { label: "对话显示", description: "工具调用和思考总结在对话中的呈现方式。" },
    skills: { label: "Skills", description: "管理 Agent 可以使用的 Skill。" },
    models: { label: "模型与账号", description: "登录模型提供方、选择输入框里显示的模型、添加自定义模型。" },
    integrations: { label: "集成", description: "连接你的工作应用。" },
    mcp: { label: "MCP 服务器", description: "连接外部工具。" },
    memory: { label: "记忆", description: "Agent 的长期记忆。" },
    workspace: { label: "工作区", description: "当前工作区、最近使用的文件夹和执行环境。" },
    archived: { label: "已归档对话", description: "找回已归档的对话。" },
    usage: { label: "使用统计", description: "模型请求与 Token 用量。" },
    storage: { label: "存储", description: "文件检查点占用的磁盘空间，以及清理。" },
    logs: { label: "日志与诊断", description: "日志级别、位置和诊断包。" },
    development: { label: "开发工具", description: "同步正式版资料、DevTools 与版本信息。仅开发版可见。" },
  },
  search: {
    placeholder: "搜索设置",
    label: "搜索设置",
    clear: "清除搜索",
    empty: "没有找到匹配的设置",
    results: "搜索结果",
  },
  updates: {
    title: "软件更新",
    versionLine: "Vela {0}",
    checkNow: "检查更新",
    checking: "正在检查更新…",
    idle: "点击「检查更新」查看是否有新版本。",
    upToDate: "已是最新版本。",
    lastChecked: "上次检查：{0}",
    available: "发现新版本 {0}。",
    availableManual: "发现新版本 {0}，可以手动下载。",
    downloadNow: "下载更新",
    downloading: "正在下载 {0}…",
    ready: "{0} 已下载并通过签名校验，重启后即可使用。",
    readyHint: "也可以继续工作，退出 Vela 时会自动完成安装。",
    restartNow: "立即重启",
    later: "稍后",
    notInstallable: "这份安装无法自动更新（例如在安装镜像里运行，或没有替换应用的权限）。请到发布页下载新版本。",
    openReleasePage: "前往发布页",
    notes: "更新内容",
    autoTitle: "自动更新",
    autoHint: "在后台检查 GitHub Release；发现新版本后自动下载并验证签名，完成后提示你重启。关闭后只在你手动检查时才会联网。",
    errors: {
      network: "无法连接 GitHub，请检查网络后重试。",
      "rate-limited": "GitHub 暂时限制了请求，请稍后再试。",
      "no-release": "没有找到可用的发布版本。",
      unsigned: "这个版本缺少签名文件，已拒绝安装。",
      signature: "更新包的签名验证失败，已拒绝安装。",
      hash: "下载的文件与已签名的校验值不一致，已丢弃。",
      extract: "无法解压更新包。",
      mismatch: "更新包与发布信息不符，已拒绝安装。",
      unknown: "更新失败，请稍后重试。",
    } as Record<UpdateErrorCode, string>,
    unavailable: "更新功能暂不可用。",
    noticeReadyTitle: "Vela {0} 已下载",
    noticeReadyHint: "重启 Vela 即可完成更新。",
    noticeManualTitle: "发现新版本 Vela {0}",
    noticeManualHint: "这份安装无法自动更新，请到发布页下载。",
  },
  storage: {
    checkpointsTitle: "文件检查点",
    checkpointsHint: "每轮对话开始和结束时记录工作区文件，用于回到之前的状态。相同内容的文件只存一份；每个对话保留最近 {0} 轮，所有检查点合计超过 {1} 时先清理最旧的。",
    measuring: "正在计算占用空间…",
    usage: "占用 {0}，来自 {1} 个对话的 {2} 个检查点。",
    clean: "清理",
    cleaning: "正在清理…",
    confirmHint: "清理会合并重复文件，并删除超出保留数量的旧检查点和不再被引用的文件。被删除的检查点无法再回退。",
    confirm: "确认清理",
    cancel: "取消",
    cleaned: "已释放 {0}，移除了 {1} 个旧检查点。",
    nothingToClean: "没有可清理的内容。",
    unavailable: "存储接口暂不可用。",
    failed: "操作失败，请重试。",
  },
  logs: {
    levelTitle: "日志级别",
    levelHint: "低于所选级别的日志不会写入。排查问题时可临时切到调试。",
    levels: { debug: "调试", info: "信息", warn: "警告", error: "错误" } as Record<"debug" | "info" | "warn" | "error", string>,
    locked: "已通过 VELA_DEBUG 环境变量强制使用调试级别。",
    folderTitle: "日志位置",
    folderHint: "每天一个文件，保留 14 天，总量上限 100 MB。密钥与令牌在写入前会被遮蔽。",
    openFolder: "打开日志文件夹",
    exportTitle: "导出诊断包",
    exportHint: "打包为 ZIP：应用日志、系统与版本信息、Git 操作记录、脱敏后的设置摘要。可附在问题反馈中。",
    includeTrace: "包含当前会话 Trace（可能含提示词、文件内容与工具输出）",
    export: "导出诊断包…",
    exporting: "正在导出…",
    exported: (path: string) => `已导出到 ${path}`,
    unavailable: "日志接口暂不可用。",
    failed: "操作失败，请重试。",
  },
  development: {
    title: "同步正式版资料",
    hint: "从正式版复制到开发版。只读取正式版；开发版已有的同名项目不会被覆盖。",
    scopeLabel: "同步范围",
    scopes: {
      conversations: { label: "会话", hint: "消息、计划、子代理历史、Trace 和检查点。" },
      settings: { label: "设置", hint: "沙箱模式、思考强度、全局指令。会覆盖开发版里不同的值。" },
      models: { label: "模型与账号", hint: "默认模型和自定义接口的结构。API 密钥与登录令牌不会同步，需要在开发版重新登录。" },
      skills: { label: "Skills", hint: "开发版没有的 Skill，连同停用状态。" },
      mcp: { label: "MCP 配置", hint: "全局服务器。环境变量和请求头的值会清空，缺少密钥的服务器先停用。" },
      memory: { label: "记忆", hint: "全局记忆。开发版已有记忆时保持不变。" },
    },
    preview: "预览",
    previewing: "正在预览…",
    previewTitle: "预览",
    previewTotal: (total: number) => `将导入 ${total} 项`,
    previewRow: (imported: number, existing: number, unavailable: number) =>
      `将导入 ${imported} 项${existing ? `，已有 ${existing} 项` : ""}${unavailable ? `，${unavailable} 项不可用` : ""}`,
    previewStale: "同步范围已更改，请重新预览。",
    nothing: "没有需要导入的内容。",
    sync: (total: number) => `同步 ${total} 项`,
    syncing: "正在同步…",
    credentials: (count: number) => `${count} 个提供方或服务器需要在开发版重新登录或填写密钥。`,
    result: (total: number) => `已导入 ${total} 项。可以在下方「同步记录」里整批撤销。`,
    restartNeeded: "部分设置在重启开发版后才会生效。",
    historyTitle: "同步记录",
    historyHint: "每次同步是一个批次，可以整批撤销。同步之后又改过的设置会保持现状。",
    historyEmpty: "还没有同步记录。",
    historyRow: (total: number) => `${total} 项`,
    unfinished: "未完成",
    rollback: "撤销",
    rollbackConfirm: "确认撤销",
    rollbackCancel: "取消",
    rollbackWarning: "会删除这批导入的会话（包括之后在其中产生的消息）、Skill 和记忆，并还原设置。",
    rollingBack: "正在撤销…",
    rollbackResult: (reverted: number, kept: number) => `已撤销 ${reverted} 项${kept ? `，${kept} 项在同步后被修改，已保持现状` : ""}。`,
    retry: "操作失败，请重试。",
    toolsTitle: "开发工具",
    toolsHint: "打开 Renderer DevTools、重新加载窗口或重启 main process。",
    openDevTools: "打开 DevTools",
    reloadWindow: "重新加载窗口",
    restartMain: "重启 main process",
    restarting: "正在重启…",
    restartMainHint: "由 electron-vite --watch 托管时，会触发重新构建并重启；重启期间窗口会短暂关闭。",
    infoTitle: "版本信息",
    infoHint: "贴进 issue 时使用。",
    infoLoading: "正在读取版本信息…",
    infoFields: {
      app: "应用", commit: "提交", branch: "分支", electron: "Electron", chrome: "Chromium", node: "Node", v8: "V8", system: "系统", home: "资料目录",
    },
    unknown: "未知",
    dirty: "有未提交改动",
    copy: "复制",
    copied: "已复制",
    copyFailed: "复制失败",
  },
  mcp: {
    title: "MCP 服务器", hint: "连接外部工具。状态与当前对话及工作区同步。",
    unavailable: "MCP 接口暂不可用。", loading: "正在读取服务器", empty: "还没有 MCP 服务器。",
    refresh: "刷新", add: "添加服务器", edit: "编辑", override: "创建覆盖配置", source: "配置来源", overridden: "已被同名配置覆盖",
    scope: "配置范围", global: "全局", project: "当前项目", noWorkspace: "选择工作区后才能添加项目服务器。",
    name: "服务器名称", transport: "连接方式", stdio: "本地进程 (stdio)", http: "HTTP",
    command: "命令", args: "参数 (JSON 数组)", env: "环境变量 (JSON 对象)", cwd: "进程工作目录", url: "服务器 URL", headers: "请求头 (JSON 对象)", oauth: "使用 OAuth 登录",
    overrideCredentials: "保存的凭据不能复制到其他配置范围。请为此覆盖配置重新填写凭据，并检查空白参数。", schema: "参数结构",
    oauthOptions: "OAuth 选项 (JSON 对象)", oauthHint: "可设置 clientId、clientSecret、callbackPort、callbackUrl、scope、clientName、authServerMetadataUrl。留空保留原配置。",
    credentialsHint: "凭据已遮盖。编辑时留空保留原值；输入 {} 清除。", newCredentialsHint: "值必须是字符串。凭据不会显示在服务器列表中。", credentialKeys: "已保存的键",
    exposure: "工具展示", deferred: "按需发现", direct: "直接提供", hidden: "隐藏", exposureHint: "按需发现：需要时加载工具；直接提供：始终加入工具列表；隐藏：不向 Agent 提供工具。",
    enabled: "启用", disabled: "已停用", enable: "启用", disable: "停用", reconnect: "重新连接", remove: "删除", removeConfirm: "确认删除此配置？删除覆盖配置后可能恢复其他来源的同名服务器。", confirmRemove: "确认删除",
    save: "保存服务器", saving: "正在保存", saved: "已保存", cancel: "取消", working: "处理中", failed: "操作失败，请重试。", loadError: "无法读取 MCP 服务器。",
    importTitle: "导入 JSON", importHint: "粘贴包含 mcpServers 的配置或服务器名称映射。先预览，再保存；同范围同名配置会被覆盖。", preview: "预览导入", importSave: "导入所选", importProgress: (done: number, total: number) => `已导入 ${done}/${total} 个服务器`,
    trustTitle: "项目 MCP 信任", trustHint: "接受前请检查以下命令和地址。信任此项目后，启用的服务器可启动本地进程或连接网络服务。", trust: "信任此项目", revokeTrust: "撤销信任", trusted: "项目已信任", untrusted: "项目尚未信任", trustChanged: "项目配置变化后需重新确认。",
    reviewConfig: "完整配置（凭据已遮盖）",
    pendingApply: "设置将在当前任务空闲时应用。",
    tools: "工具", toolsEmpty: "尚未发现工具。连接服务器后刷新。", readOnly: "标记为只读", readOnlyHint: "只读声明会影响权限判断。仅在确认工具不会写文件、修改远程数据或产生其他副作用后开启。", confirmReadOnly: "确认工具只读", clearReadOnly: "取消只读标记", serverReadOnly: "服务器声明只读", userReadOnly: "已确认只读",
    login: "OAuth 登录", retryLogin: "重试登录", cancelLogin: "取消登录", logout: "退出登录", loginPending: "正在等待浏览器授权", authenticated: "已登录", loginFailed: "登录失败，可重试。",
    statuses: { connected: "已连接", connecting: "正在连接", disconnected: "未连接", disabled: "已停用", error: "连接出错", "auth-required": "需要登录", "authenticating": "正在登录", "untrusted": "等待项目信任", "idle": "空闲" },
    fields: { import: "导入 JSON", config: "配置", name: "服务器名称", transport: "连接方式", command: "命令", args: "参数", env: "环境变量", cwd: "工作目录", url: "URL", headers: "请求头", oauth: "OAuth", enabled: "启用状态", exposure: "工具展示" },
    errors: { json: "请输入有效 JSON。", object: "请输入 JSON 对象。", strings: "只能包含字符串值（参数应为字符串数组）。", required: "请填写此字段（名称只支持字母、数字、下划线和连字符）。", transport: "请选择 stdio 或 HTTP。", url: "请输入不含用户名或密码的 HTTP / HTTPS 地址。", exposure: "请选择按需发现、直接提供或隐藏。", boolean: "值必须是 true 或 false。", empty: "没有可导入的服务器。", port: "回调端口必须是 1–65535 之间的整数。" },
  },
  memory: {
    title: "记忆",
    enabledLabel: "启用记忆",
    enabledHint: "关闭后保留已有记忆，仅禁止 Agent 读取和写入。你仍可在这里查看和编辑。",
    enabledStatus: "已开启",
    disabledStatus: "已关闭",
    toggleSaving: "正在保存开关…",
    hint: "Agent 每次执行前读取全局与当前项目记忆，并在对话中自动保存明确的长期偏好、项目约定和已确认决策。你可以在这里查看、编辑或删除；修改在下一次执行生效。",
    unavailable: "记忆接口暂不可用。",
    tabs: { all: "全部记忆", global: "全局记忆", project: "项目记忆" },
    loading: "正在读取记忆…",
    loadingFile: "正在读取文件…",
    refresh: "刷新",
    allHint: "全局记忆和已登记工作区的项目记忆。点击一项进入编辑；只有全局和当前项目的内容会进入模型上下文。",
    globalHint: "全局记忆跨项目生效，保存在当前 Vela 资料目录的 MEMORY.md。",
    projectHint: "项目记忆跟随会话自己的工作区，保存在工作区的 .vela/MEMORY.md；worktree 各自独立。",
    noWorkspace: "还没有登记的工作区，无法管理项目记忆。先打开一个工作区或新建对话。",
    projectLabel: "项目",
    scopeGlobal: "全局",
    scopeProject: "项目",
    global: "全局记忆",
    statusLoaded: (bytes: number) => `已保存 · ${bytes} 字节`,
    statusMissing: "未创建，保存后创建",
    statusFailed: "读取失败",
    fileStatus: (bytes: number) => `已保存 · ${bytes} 字节`,
    revisionLabel: "版本",
    dirty: "有未保存的修改",
    draftBadge: "草稿",
    editorLabel: "记忆内容",
    editorHint: "普通 Markdown 文本，最多 16 KiB，不会执行嵌入的 HTML；Command/Ctrl + S 保存",
    byteCount: (bytes: number) => `${bytes} 字节`,
    save: "保存",
    saving: "正在保存…",
    saved: "已保存。",
    cancel: "取消",
    clear: "清空内容",
    remove: "删除文件",
    removeConfirm: "删除后文件会从磁盘移除，无法撤销。",
    confirmRemove: "确认删除",
    removing: "正在删除…",
    removed: "已删除记忆文件。",
    reveal: "在文件中显示",
    revealError: "找不到可打开的文件位置。",
    reload: "重新加载",
    conflict: "文件已被其他会话或外部编辑更新。",
    overLimit: "内容超过 16 KiB，请先精简再保存。",
    errors: {
      "invalid-target": "记忆目标不正确或没有登记。",
      "invalid-content": "记忆内容或版本不正确。",
      "content-too-large": "文件超过 16 KiB 上限，请先精简内容。",
      "invalid-encoding": "文件不是有效的 UTF-8 文本，请用外部编辑器修复。",
      "unsafe-path": "记忆路径不安全，已拒绝访问。",
      "not-a-file": "记忆路径不是普通文件。",
      "unavailable": "工作区或目录不存在，无法访问。",
      "conflict": "文件已被其他会话或外部编辑更新；草稿已保留，请重新加载后再合并。",
      "busy": "文件正被另一个 Vela 进程写入；若上次写入已中断，请手动移除同目录的 .lock 文件。",
      "io-error": "读写失败，请检查文件权限后重试。",
    },
  },
  archived: {
    title: "已归档对话",
    hint: "归档的对话不在侧边栏显示,历史仍然保留。在这里搜索后取消归档即可恢复。",
    searchPlaceholder: "搜索标题或工作区",
    empty: "还没有归档的对话。把鼠标悬停在侧边栏的会话上即可归档。",
    searchEmpty: "没有符合条件的归档对话。",
    workspace: "工作区",
    unarchive: "取消归档",
    unarchived: "对话已恢复到侧边栏",
  },
  agent: {
    model: "默认模型",
    modelHint: "新对话默认使用此模型。你也可以在输入框中为当前对话切换模型。",
    modelEmpty: "未选择",
    modelMissing: "还没有可用模型。先在「模型与账号」里登录或添加。",
    modelUnavailable: "当前默认模型还不能使用",
    thinking: "默认思考强度",
    thinkingHint: "模型可能不支持所有思考强度，可选项会根据当前模型调整。",
    levels: {
      off: "关闭",
      minimal: "最低",
      low: "低",
      medium: "中",
      high: "高",
      xhigh: "极高",
      max: "最高",
    },
    newConversation: "新对话使用的选择",
    newConversationHint: "「设置默认」让新对话使用上面的默认模型和思考强度；「上次使用」沿用最近一次在对话里用过的模型和思考强度，那个模型不可用时回退到默认。",
    newConversationDefault: "设置默认",
    newConversationLastUsed: "上次使用",
    instructions: "额外指令",
    instructionsHint: "为 Agent 补充长期遵循的偏好，仅对新建对话生效。",
    instructionsPlaceholder: "例如：请优先用简洁的中文回答；修改代码前先阅读相关文件；不确定时先说明你的假设。",
    skills: "Skills",
    skillsHint: "把包含 SKILL.md 的目录放在下方路径。新对话会按名称和描述决定是否读取全文。在输入框输入 / 可以选择 Skill，也可以直接发送 /skill:名称。每个 Skill 都能单独停用；Vela 目录里的 Skill 还可以删除。",
    skillsEmpty: "还没有 Skill。",
    openSkills: "打开 Skill 目录",
    skillsLoadError: "无法读取 Skill",
    skillCommandOnly: "仅命令",
    skillOrigins: {
      user: "用户",
      project: "项目",
      agents: "~/.agents",
    },
    skillEnabled: "已启用",
    skillDisabled: "已停用",
    skillDisable: "停用",
    skillEnable: "启用",
    skillDelete: "删除",
    skillDeleteConfirm: "确认删除",
    skillToggleHint: "停用后新对话不再加载这个 Skill，也不能用 /skill:名称 调用；已打开的对话会在下次发送前刷新。",
    skillDeleteHint: "从 Vela Skill 目录删除文件，无法撤销。",
    skillDeleteNote: "项目、~/.agents 等目录里的 Skill 只能停用；要删除请到对应目录操作。",
    migrate: "从 Codex / Claude Code 迁移",
    migrateTitle: "选择要迁移的 Skill",
    migrateHint: "勾选要复制到 Vela 的 Skill。新的 Skill 已预先勾选。原来的文件会保留；勾选已存在的同名 Skill 会覆盖。",
    migrateEmpty: "没有在 Codex 或 Claude Code 中找到 Skill。",
    migrateLoadError: "无法读取可迁移的 Skill",
    migrateSources: {
      codex: "Codex",
      claude: "Claude Code",
    },
    migrateScopes: {
      user: "用户",
      project: "当前项目",
    },
    migrateStates: {
      present: "已存在",
      loaded: "已加载",
    },
    migrateReplaceNote: "勾选后覆盖 Vela 中的同名 Skill",
    migrateLoadedNote: "Vela 已从原位置加载",
    migrateLocalNote: "已经在 Vela 的 Skill 目录里",
    migrateSameName: "与前面的选项同名，只会迁移第一个",
    migrateSelectAll: "全选",
    migrateSelectNone: "全不选",
    migrateSelected: (count: number) => `已选 ${count} 个`,
    migrateConfirm: "迁移所选",
    migrating: "正在迁移",
    migrateCancel: "取消",
    migrateClose: "关闭",
    migrateLoading: "正在查找 Skill",
    migrateDone: (count: number) => `已迁移 ${count} 个 Skill`,
    migrateNone: "没有迁移任何 Skill",
    migrateSkip: {
      "not-found": "找不到这个 Skill",
      unsafe: "这个 Skill 不在可迁移的目录里",
      "already-local": "已经在 Vela 的 Skill 目录里",
      duplicate: "与其他所选 Skill 同名，已跳过",
      failed: "复制失败",
    },
    autosaveNote: "停止输入或离开输入框后自动保存。",
    saving: "正在保存",
    saved: "已保存",
    loadError: "无法读取 Agent 设置",
  },
  models: {
    connected: "已连接的提供方",
    empty: "还没有提供方。可以在下方添加自定义模型。",
    connectedStatus: "已连接",
    disconnectedStatus: "未连接",
    modelCount: (count: number) => `${count} 个可用模型`,
    visibility: "输入框中的模型",
    visibilityHint: "取消勾选后，该模型不会出现在主页输入框的模型列表里，随时可以重新勾选。当前正在使用的模型仍会显示，方便切换。",
    visibilityEmpty: "还没有可用模型。先登录提供方或添加模型，再选择显示哪些。",
    visibilityHidden: "已隐藏",
    visibilityShow: "在输入框中显示",
    visibilityHide: "在输入框中隐藏",
    visibilityShowAll: (count: number) => `全部显示（已隐藏 ${count} 个）`,
    login: "登录",
    apiKey: "填写密钥",
    logout: "退出登录",
    remove: "移除",
    confirmRemove: "确认移除",
    add: "添加自定义模型",
    providerName: "提供方名称",
    providerPlaceholder: "例如 Ollama",
    baseUrl: "接口地址",
    baseUrlPlaceholder: "http://127.0.0.1:11434/v1",
    api: "接口类型",
    apiKeyField: "API 密钥",
    apiKeyPlaceholder: "已有接口可以留空",
    modelId: "模型 ID",
    modelIdPlaceholder: "qwen2.5-coder:7b",
    displayName: "显示名称",
    displayNamePlaceholder: "在列表中显示的名称",
    optional: "可选",
    reasoning: "支持推理",
    context: "上下文长度",
    maxOutput: "最大输出长度",
    optionalPlaceholder: "可选",
    submit: "测试并添加模型",
    submitting: "正在测试",
    added: "已添加",
    keyHint: "API 密钥会保存在本机，用于连接该模型提供方。",
    providerInvalid: "需要填写提供方名称。",
    apis: {
      "openai-completions": "OpenAI Chat Completions",
      "openai-responses": "OpenAI Responses",
      "anthropic-messages": "Anthropic Messages",
      "google-generative-ai": "Google Generative AI",
    },
  },
  permissions: {
    title: "执行权限",
    ask: "每次询问",
    askHint: "运行终端命令前需要你逐次批准。修改工作区外的文件前也需要批准；工作区内的文件修改无需逐次确认。",
    smart: "帮我批准",
    smartHint: "先由当前对话选择的模型判断风险。只有风险操作或判断失败时才需要你批准，低风险操作直接执行。",
    full: "完全访问",
    fullHint: "在当前工具权限范围内执行命令和文件修改，不再逐项询问。",
    note: "执行权限会影响 Agent 能自动完成的操作。你可以随时在输入框旁切换。",
  },
  workspace: {
    current: "当前工作区",
    empty: "尚未选择工作区",
    choose: "选择文件夹",
    close: "关闭工作区",
    recent: "最近使用",
    recentEmpty: "还没有最近使用的文件夹。",
    removeRecent: "从最近使用中移除",
    environment: "执行环境",
    local: "本地",
    localHint: "直接在当前工作区中操作。",
    worktree: "工作树",
    worktreeHint: "使用独立的 Git worktree 操作，适合隔离代码改动。",
    sandbox: "沙箱",
    remote: "远程",
    soon: "即将支持",
    switching: "切换中",
  },
  appearance: {
    theme: "明暗模式",
    system: "跟随系统",
    light: "浅色",
    dark: "深色",
    palette: "主题",
    paletteHint: "浅色和深色各选一个主题。跟随系统时，会随系统外观在两者之间切换。",
    lightThemes: "浅色主题",
    darkThemes: "深色主题",
    inUse: "使用中",
    themes: {
      daylight: { name: "晴空", hint: "冷白底色，湛蓝点缀" },
      paper: { name: "宣纸", hint: "温润米色，赤陶点缀" },
      celadon: { name: "青瓷", hint: "淡青釉色，松石绿点缀" },
      midnight: { name: "夜航", hint: "深蓝夜色，冷静专注" },
      graphite: { name: "石墨", hint: "中性近黑，薰衣草紫点缀" },
      ember: { name: "余烬", hint: "暖炭底色，余火橙点缀" },
    },
    language: "语言",
    soundEffects: "任务音效",
    soundEffectsHint: "任务出错、完成、需要回答问题或确认权限时播放短提示音，也适用于后台对话。",
    soundEffectsOn: "开启",
    soundEffectsOff: "关闭",
    soundPreview: "试听音效",
    soundError: "出错",
    soundComplete: "完成",
    soundQuestion: "回答问题",
    soundPermission: "确认权限",
    zh: "简体中文",
    en: "English",
    infoLayout: "右侧信息布局",
    infoLayoutHint: "选择固定半透明边栏，或将环境卡片悬浮在对话右上角，点击输入框下方的上下文圆环查看用量详情。",
    infoLayoutSidebar: "半透明边栏",
    infoLayoutFloating: "悬浮信息",
    conversationLinkTarget: "对话链接打开方式",
    conversationLinkHint: "点击对话中的网页链接时，在右侧新建浏览器标签页，或使用系统默认浏览器。",
    linkEmbedded: "内置浏览器",
    linkExternal: "系统浏览器",
    sidebarItems: "侧边栏选项卡",
    sidebarItemsHint: "选择左侧边栏顶部显示哪些入口。",
    sidebarItemLabels: { prInbox: "Pull Requests", scheduledTasks: "定时任务", newChat: "新对话", recipes: "任务配方" },
    composerCapsules: "输入框选项胶囊背景",
    composerCapsulesHint: "为添加附件、对话模式、执行权限、思考强度和模型选项显示胶囊背景。",
    composerCapsulesOff: "关闭",
    composerCapsulesOn: "开启",
    sendButtonIcon: "发送按钮图标",
    sendButtonIconPaperPlane: "纸飞机",
    sendButtonIconArrowUp: "向上箭头",
    toolDisplay: "工具调用显示",
    toolDisplayHint: "「卡片」为每个工具显示可展开的卡片；「紧凑」每个工具一行，调用超过一次时自动折叠成摘要，点击文件名可在右侧预览。",
    toolCard: "卡片",
    toolCompact: "紧凑",
    toolFold: "工具折叠方式",
    toolFoldHint: "「按 Assistant 消息」只合并同一条消息里的连续工具；「按位置关系」允许相邻消息的工具合并成一组，思考、正文、用户消息和交互卡片仍会打断分组。",
    toolFoldMessage: "按 Assistant 消息",
    toolFoldPosition: "按位置关系",
    toolProcessDetails: "过程行耗时与折叠记忆",
    toolProcessDetailsHint: "开启后，紧凑模式的过程行显示每个工具调用与整轮的总耗时，并记住每条「展开 / 收起」状态，重开聊天后保持不变。耗时取自已有轨迹，缺少记录的旧会话不显示标签。",
    toolProcessDetailsOff: "关闭",
    toolProcessDetailsOn: "开启",
    thinkingSummary: "思考总结",
    thinkingSummaryHint: "开启后，自动总结新完成的思考。总结使用界面语言，历史思考可手动生成。每段总结会额外调用一次模型。",
    thinkingSummaryOff: "关闭",
    thinkingSummaryOn: "自动生成",
    thinkingSummaryModel: "思考总结模型",
    thinkingSummaryModelHint: "默认跟随当前对话，也可指定独立模型用于自动和手动总结。更改后对新生成的总结生效，已有总结会保留。",
    thinkingSummaryModelCurrent: "跟随当前对话模型",
    thinkingSummaryModelConfigure: "可在「模型与账号」中添加自定义模型，配置后即可在此选择。",
    thinkingSummaryModelUnavailable: "不可用",
    thinkingSummaryModelMissing: "所选模型不可用。请在「模型与账号」中重新配置，或选择其他模型。",
    thinkingSummaryStyle: "总结显示方式",
    thinkingSummaryStyleHint: "「跟在思考后」在“思考”右侧显示一行总结；「作为标题」用总结替换“思考”标题，点击后展开完整总结和思考内容；「跟随回复」把总结按回复正文样式显示，点击末尾的展开图标查看思考内容。",
    thinkingSummaryStyleInline: "跟在思考后",
    thinkingSummaryStyleHeadline: "作为标题",
    thinkingSummaryStyleProse: "跟随回复",
    fileIconTheme: "文件图标",
    fileIconThemeHint: "选择文件预览和工具调用中使用的图标样式。",
    devicon: "Devicon",
    materialIconTheme: "Material Icon Theme",
    shortcuts: "快捷键",
    shortcutsHint: "这些是当前可用的快捷键。",
    items: {
      sidebar: "折叠侧边栏",
      panel: "折叠右侧面板",
      settings: "打开设置",
      search: "搜索设置（在设置中）",
      close: "关闭设置或对话框",
      send: "发送消息",
      newline: "换行",
    },
  },
};

const en: typeof zh = {
  title: "Settings",
  done: "Done",
  open: "Settings",
  groups: {
    general: "General",
    agent: "Agent",
    extensions: "Models & extensions",
    data: "Data & workspace",
    development: "Development",
  },
  pages: {
    appearance: { label: "Appearance", description: "Theme, palette and file icons." },
    interface: { label: "Interface", description: "Language, layout, sidebar, composer and sounds." },
    shortcuts: { label: "Shortcuts", description: "The keyboard shortcuts that work today." },
    updates: { label: "About & updates", description: "Current version, update checks and automatic updates." },
    defaults: { label: "Defaults & permissions", description: "Default model, thinking level, extra instructions and execution permissions for new conversations." },
    display: { label: "Conversation display", description: "How tool calls and thinking summaries appear in a conversation." },
    skills: { label: "Skills", description: "Manage the skills the agent can use." },
    models: { label: "Models & accounts", description: "Sign in to providers, choose which models show in the composer, and add custom models." },
    integrations: { label: "Integrations", description: "Connect your workspace apps." },
    mcp: { label: "MCP servers", description: "Connect external tools." },
    memory: { label: "Memory", description: "The agent's long-term memory." },
    workspace: { label: "Workspace", description: "The current workspace, recent folders and execution environment." },
    archived: { label: "Archived chats", description: "Bring archived conversations back." },
    usage: { label: "Usage statistics", description: "Model requests and token usage." },
    storage: { label: "Storage", description: "Disk space used by file checkpoints, and cleanup." },
    logs: { label: "Logs & diagnostics", description: "Log level, location and diagnostics export." },
    development: { label: "Developer tools", description: "Sync production data, DevTools and version information. Development builds only." },
  },
  search: {
    placeholder: "Search settings",
    label: "Search settings",
    clear: "Clear search",
    empty: "No matching settings",
    results: "Search results",
  },
  updates: {
    title: "Software update",
    versionLine: "Vela {0}",
    checkNow: "Check for updates",
    checking: "Checking for updates…",
    idle: "Choose “Check for updates” to see whether a newer version is available.",
    upToDate: "You're up to date.",
    lastChecked: "Last checked: {0}",
    available: "Version {0} is available.",
    availableManual: "Version {0} is available to download.",
    downloadNow: "Download update",
    downloading: "Downloading {0}…",
    ready: "{0} has been downloaded and its signature verified. Restart to use it.",
    readyHint: "You can keep working. It installs automatically when you quit Vela.",
    restartNow: "Restart now",
    later: "Later",
    notInstallable: "This installation can't update itself (for example it runs from a disk image, or Vela can't replace the app here). Download the new version from the release page.",
    openReleasePage: "Open release page",
    notes: "What's new",
    autoTitle: "Automatic updates",
    autoHint: "Checks GitHub Releases in the background, downloads new versions and verifies their signature, then asks you to restart. When off, Vela only goes online when you check manually.",
    errors: {
      network: "Couldn't reach GitHub. Check your network and try again.",
      "rate-limited": "GitHub is temporarily limiting requests. Try again later.",
      "no-release": "No published release was found.",
      unsigned: "This release has no signature files, so it was not installed.",
      signature: "The update's signature could not be verified, so it was not installed.",
      hash: "The downloaded file doesn't match the signed checksum and was discarded.",
      extract: "The update could not be unpacked.",
      mismatch: "The update doesn't match its release information, so it was not installed.",
      unknown: "The update failed. Please try again later.",
    } as Record<UpdateErrorCode, string>,
    unavailable: "Updates are not available.",
    noticeReadyTitle: "Vela {0} has been downloaded",
    noticeReadyHint: "Restart Vela to finish updating.",
    noticeManualTitle: "Vela {0} is available",
    noticeManualHint: "This installation can't update itself. Download it from the release page.",
  },
  storage: {
    checkpointsTitle: "File checkpoints",
    checkpointsHint: "Workspace files are recorded at the start and end of every turn so you can return to an earlier state. Identical files are stored once; each conversation keeps its latest {0} turns, and the oldest checkpoints go first once all of them together exceed {1}.",
    measuring: "Measuring disk usage…",
    usage: "Using {0} for {2} checkpoints from {1} conversations.",
    clean: "Clean up",
    cleaning: "Cleaning up…",
    confirmHint: "Cleaning merges duplicate files and deletes checkpoints beyond the retention limit, along with files nothing refers to any more. Deleted checkpoints can no longer be rewound to.",
    confirm: "Confirm cleanup",
    cancel: "Cancel",
    cleaned: "Freed {0} and removed {1} old checkpoints.",
    nothingToClean: "Nothing to clean up.",
    unavailable: "The storage API is not available yet.",
    failed: "The operation failed. Please try again.",
  },
  logs: {
    levelTitle: "Log level",
    levelHint: "Entries below the selected level are not written. Switch to Debug temporarily while troubleshooting.",
    levels: { debug: "Debug", info: "Info", warn: "Warning", error: "Error" },
    locked: "Debug level is forced by the VELA_DEBUG environment variable.",
    folderTitle: "Log location",
    folderHint: "One file per day, kept for 14 days, capped at 100 MB in total. Keys and tokens are masked before writing.",
    openFolder: "Open logs folder",
    exportTitle: "Export diagnostics",
    exportHint: "Creates a ZIP with app logs, system and version info, Git operation records and a redacted settings summary. Attach it to a bug report.",
    includeTrace: "Include the current conversation Trace (may contain prompts, file contents and tool output)",
    export: "Export diagnostics…",
    exporting: "Exporting…",
    exported: (path: string) => `Exported to ${path}`,
    unavailable: "The logging API is not available yet.",
    failed: "The operation failed. Please try again.",
  },
  development: {
    title: "Sync production data",
    hint: "Copy from the production app into this development app. Production is only read; matching items in the development app are never overwritten.",
    scopeLabel: "What to sync",
    scopes: {
      conversations: { label: "Conversations", hint: "Messages, plans, subagent history, traces and checkpoints." },
      settings: { label: "Settings", hint: "Sandbox mode, thinking level and global instructions. Differing values in the development app are replaced." },
      models: { label: "Models and accounts", hint: "The default model and custom endpoint structure. API keys and sign-in tokens are not synced; sign in again in the development app." },
      skills: { label: "Skills", hint: "Skills the development app does not have, including their disabled state." },
      mcp: { label: "MCP configuration", hint: "Global servers. Environment variable and header values are cleared, and servers missing secrets start disabled." },
      memory: { label: "Memory", hint: "Global memory. Existing development memory is left unchanged." },
    },
    preview: "Preview",
    previewing: "Previewing…",
    previewTitle: "Preview",
    previewTotal: (total: number) => `${total} ${total === 1 ? "item" : "items"} will be imported`,
    previewRow: (imported: number, existing: number, unavailable: number) =>
      `${imported} to import${existing ? `, ${existing} already present` : ""}${unavailable ? `, ${unavailable} unavailable` : ""}`,
    previewStale: "The selection changed. Preview again.",
    nothing: "There is nothing to import.",
    sync: (total: number) => `Sync ${total} ${total === 1 ? "item" : "items"}`,
    syncing: "Syncing…",
    credentials: (count: number) => `${count} ${count === 1 ? "provider or server needs" : "providers or servers need"} a new sign-in or secret in the development app.`,
    result: (total: number) => `Imported ${total} ${total === 1 ? "item" : "items"}. You can undo the whole batch under Sync history below.`,
    restartNeeded: "Some settings take effect after the development app restarts.",
    historyTitle: "Sync history",
    historyHint: "Each sync is a batch you can undo as a whole. Settings changed after the sync stay as they are.",
    historyEmpty: "No syncs yet.",
    historyRow: (total: number) => `${total} ${total === 1 ? "item" : "items"}`,
    unfinished: "Unfinished",
    rollback: "Undo",
    rollbackConfirm: "Confirm undo",
    rollbackCancel: "Cancel",
    rollbackWarning: "This removes the imported conversations (including messages added to them since), skills and memory, and restores settings.",
    rollingBack: "Undoing…",
    rollbackResult: (reverted: number, kept: number) => `Undid ${reverted} ${reverted === 1 ? "item" : "items"}${kept ? `; ${kept} changed after the sync and were left as they are` : ""}.`,
    retry: "The operation failed. Please try again.",
    toolsTitle: "Developer tools",
    toolsHint: "Open the renderer DevTools, reload the window or restart the main process.",
    openDevTools: "Open DevTools",
    reloadWindow: "Reload window",
    restartMain: "Restart main process",
    restarting: "Restarting…",
    restartMainHint: "When managed by electron-vite --watch this triggers a rebuild and restart. The window closes briefly.",
    infoTitle: "Version information",
    infoHint: "Paste it into an issue.",
    infoLoading: "Reading version information…",
    infoFields: {
      app: "App", commit: "Commit", branch: "Branch", electron: "Electron", chrome: "Chromium", node: "Node", v8: "V8", system: "System", home: "Data folder",
    },
    unknown: "Unknown",
    dirty: "uncommitted changes",
    copy: "Copy",
    copied: "Copied",
    copyFailed: "Copy failed",
  },
  mcp: {
    title: "MCP servers", hint: "Connect external tools. Status follows the current conversation and workspace.",
    unavailable: "The MCP API is not available yet.", loading: "Loading servers", empty: "No MCP servers yet.",
    refresh: "Refresh", add: "Add server", edit: "Edit", override: "Create override", source: "Configuration source", overridden: "Overridden by another configuration with this name",
    scope: "Configuration scope", global: "Global", project: "Current project", noWorkspace: "Select a workspace to add project servers.",
    name: "Server name", transport: "Transport", stdio: "Local process (stdio)", http: "HTTP",
    command: "Command", args: "Arguments (JSON array)", env: "Environment variables (JSON object)", cwd: "Process working directory", url: "Server URL", headers: "Headers (JSON object)", oauth: "Use OAuth login",
    overrideCredentials: "Saved credentials cannot be copied to another scope. Enter credentials for this override and review any empty arguments.", schema: "Input schema",
    oauthOptions: "OAuth options (JSON object)", oauthHint: "Optional clientId, clientSecret, callbackPort, callbackUrl, scope, clientName, and authServerMetadataUrl. Leave blank to preserve saved options.",
    credentialsHint: "Credentials are masked. Leave blank to preserve saved values; enter {} to clear them.", newCredentialsHint: "Values must be strings. Credentials are not shown in the server list.", credentialKeys: "Saved keys",
    exposure: "Tool exposure", deferred: "Discover as needed", direct: "Always available", hidden: "Hidden", exposureHint: "Discover as needed loads tools when required; always available adds them directly to the tool list; hidden keeps them from the agent.",
    enabled: "Enabled", disabled: "Disabled", enable: "Enable", disable: "Disable", reconnect: "Reconnect", remove: "Delete", removeConfirm: "Delete this configuration? Removing an override may restore a server with the same name from another source.", confirmRemove: "Confirm delete",
    save: "Save server", saving: "Saving", saved: "Saved", cancel: "Cancel", working: "Working", failed: "The action failed. Please try again.", loadError: "Could not load MCP servers.",
    importTitle: "Import JSON", importHint: "Paste a configuration containing mcpServers, or a map of server names. Preview before saving. Matching names in the same scope will be replaced.", preview: "Preview import", importSave: "Import selected", importProgress: (done: number, total: number) => `Imported ${done}/${total} servers`,
    trustTitle: "Project MCP trust", trustHint: "Review these commands and URLs before accepting. Trusting this project lets enabled servers start local processes or connect to network services.", trust: "Trust this project", revokeTrust: "Revoke trust", trusted: "Project trusted", untrusted: "Project not trusted", trustChanged: "Review again when the project configuration changes.",
    reviewConfig: "Full configuration (credentials masked)",
    pendingApply: "Changes will apply when the current task is idle.",
    tools: "Tools", toolsEmpty: "No tools discovered yet. Connect the server and refresh.", readOnly: "Mark as read-only", readOnlyHint: "A read-only declaration affects permission checks. Confirm only if the tool does not write files, change remote data, or cause other side effects.", confirmReadOnly: "Confirm read-only", clearReadOnly: "Clear read-only override", serverReadOnly: "Server declares read-only", userReadOnly: "Confirmed read-only",
    login: "Log in with OAuth", retryLogin: "Retry login", cancelLogin: "Cancel login", logout: "Log out", loginPending: "Waiting for browser authorization", authenticated: "Logged in", loginFailed: "Login failed. You can retry.",
    statuses: { connected: "Connected", connecting: "Connecting", disconnected: "Disconnected", disabled: "Disabled", error: "Connection error", "auth-required": "Login required", "authenticating": "Logging in", "untrusted": "Awaiting project trust", "idle": "Idle" },
    fields: { import: "Import JSON", config: "Configuration", name: "Server name", transport: "Transport", command: "Command", args: "Arguments", env: "Environment variables", cwd: "Working directory", url: "URL", headers: "Headers", oauth: "OAuth", enabled: "Enabled", exposure: "Tool exposure" },
    errors: { json: "Enter valid JSON.", object: "Enter a JSON object.", strings: "Values must be strings (arguments must be an array of strings).", required: "Fill in this field (names use letters, numbers, underscores, and hyphens).", transport: "Choose stdio or HTTP.", url: "Enter an HTTP / HTTPS URL without a username or password.", exposure: "Choose deferred, direct, or hidden exposure.", boolean: "The value must be true or false.", empty: "No servers to import.", port: "The callback port must be an integer from 1 to 65535." },
  },
  memory: {
    title: "Memory",
    enabledLabel: "Enable memory",
    enabledHint: "Turning this off keeps existing memory and stops the agent from reading or writing it. You can still review and edit it here.",
    enabledStatus: "On",
    disabledStatus: "Off",
    toggleSaving: "Saving preference…",
    hint: "The agent reads global and current-project memory before every run and automatically saves clear long-term preferences, project conventions, and confirmed decisions during conversations. Review, edit, or delete them here; changes apply to the next run.",
    unavailable: "The memory API is not available.",
    tabs: { all: "All memory", global: "Global memory", project: "Project memory" },
    loading: "Loading memory…",
    loadingFile: "Loading file…",
    refresh: "Refresh",
    allHint: "Global memory and project memory for registered workspaces. Open an entry to edit it; only global and current-project content enters the model context.",
    globalHint: "Global memory applies to every project and lives in MEMORY.md in the current Vela profile.",
    projectHint: "Project memory follows the conversation's own workspace at .vela/MEMORY.md; worktrees stay separate.",
    noWorkspace: "No registered workspace yet, so project memory cannot be managed. Open a workspace or start a conversation first.",
    projectLabel: "Project",
    scopeGlobal: "Global",
    scopeProject: "Project",
    global: "Global memory",
    statusLoaded: (bytes: number) => `Saved · ${bytes} bytes`,
    statusMissing: "Not created; saving will create it",
    statusFailed: "Read failed",
    fileStatus: (bytes: number) => `Saved · ${bytes} bytes`,
    revisionLabel: "version",
    dirty: "Unsaved changes",
    draftBadge: "Draft",
    editorLabel: "Memory content",
    editorHint: "Plain Markdown up to 16 KiB; embedded HTML is not executed. Command/Ctrl + S saves",
    byteCount: (bytes: number) => `${bytes} bytes`,
    save: "Save",
    saving: "Saving…",
    saved: "Saved.",
    cancel: "Cancel",
    clear: "Clear content",
    remove: "Delete file",
    removeConfirm: "The file will be removed from disk. This cannot be undone.",
    confirmRemove: "Confirm delete",
    removing: "Deleting…",
    removed: "Memory file deleted.",
    reveal: "Reveal in file manager",
    revealError: "No folder to open.",
    reload: "Reload",
    conflict: "The file changed in another conversation or an external editor.",
    overLimit: "Content exceeds 16 KiB. Shorten it before saving.",
    errors: {
      "invalid-target": "The memory target is incorrect or not registered.",
      "invalid-content": "The memory content or revision is incorrect.",
      "content-too-large": "The file exceeds the 16 KiB limit. Shorten it first.",
      "invalid-encoding": "The file is not valid UTF-8. Fix it in an external editor.",
      "unsafe-path": "The memory path is unsafe and access was refused.",
      "not-a-file": "The memory path is not a regular file.",
      "unavailable": "The workspace or directory is unavailable.",
      "conflict": "The file changed in another conversation or an external editor. Your draft is kept; reload before merging.",
      "busy": "Another Vela process is writing this file. If a write was interrupted, remove the .lock file in the same folder manually.",
      "io-error": "The read or write failed. Check file permissions and retry.",
    },
  },
  archived: {
    title: "Archived conversations",
    hint: "Archived conversations are hidden from the sidebar but keep their history. Search here and unarchive to restore.",
    searchPlaceholder: "Search titles or workspaces",
    empty: "No archived conversations yet. Hover a chat in the sidebar to archive it.",
    searchEmpty: "No archived conversations match.",
    workspace: "Workspace",
    unarchive: "Unarchive",
    unarchived: "Conversation restored to the sidebar",
  },
  agent: {
    model: "Default model",
    modelHint: "New conversations use this model. You can still switch the model for the current conversation from the input.",
    modelEmpty: "None selected",
    modelMissing: "No models are available yet. Log in or add one under Models & accounts.",
    modelUnavailable: "The current default model is not available",
    thinking: "Default thinking level",
    thinkingHint: "A model may not support every level. The choices follow the selected model.",
    levels: {
      off: "Off",
      minimal: "Minimal",
      low: "Low",
      medium: "Medium",
      high: "High",
      xhigh: "Extra high",
      max: "Max",
    },
    newConversation: "What new conversations start with",
    newConversationHint: "“Settings default” starts new conversations with the default model and reasoning effort above. “Last used” reuses the model and reasoning effort from your most recent conversation, falling back to the default when that model is unavailable.",
    newConversationDefault: "Settings default",
    newConversationLastUsed: "Last used",
    instructions: "Extra instructions",
    instructionsHint: "Long-term preferences for the agent. They apply only to new conversations.",
    instructionsPlaceholder: "For example: answer in concise English; read the relevant files before editing code; state your assumptions when you are unsure.",
    skills: "Skills",
    skillsHint: "Place a directory containing SKILL.md at the path below. New conversations see each skill’s name and description, then read the full file when it applies. Type / in the composer to choose a skill, or send /skill:name. Each skill can be disabled on its own; skills in Vela’s folder can also be deleted.",
    skillsEmpty: "No skills yet.",
    openSkills: "Open skills folder",
    skillsLoadError: "Could not load skills",
    skillCommandOnly: "Command only",
    skillOrigins: {
      user: "User",
      project: "Project",
      agents: "~/.agents",
    },
    skillEnabled: "Enabled",
    skillDisabled: "Disabled",
    skillDisable: "Disable",
    skillEnable: "Enable",
    skillDelete: "Delete",
    skillDeleteConfirm: "Confirm delete",
    skillToggleHint: "Disabled skills are not loaded into new conversations and cannot be invoked with /skill:name. Open conversations refresh before the next message.",
    skillDeleteHint: "Deletes the files from Vela’s skills folder. This cannot be undone.",
    skillDeleteNote: "Skills from project or ~/.agents folders can only be disabled here. Delete them in their own folder.",
    migrate: "Migrate from Codex / Claude Code",
    migrateTitle: "Choose skills to migrate",
    migrateHint: "Choose which skills to copy into Vela. New skills start selected. The originals stay where they are; selecting an existing skill replaces that copy.",
    migrateEmpty: "No skills were found in Codex or Claude Code.",
    migrateLoadError: "Could not read skills to migrate",
    migrateSources: {
      codex: "Codex",
      claude: "Claude Code",
    },
    migrateScopes: {
      user: "User",
      project: "Current project",
    },
    migrateStates: {
      present: "Already exists",
      loaded: "Already loaded",
    },
    migrateReplaceNote: "Selecting this replaces the Vela copy",
    migrateLoadedNote: "Vela already loads this from its current location",
    migrateLocalNote: "Already in Vela’s skills folder",
    migrateSameName: "Same folder as an earlier choice; only the first one is migrated",
    migrateSelectAll: "Select all",
    migrateSelectNone: "Clear",
    migrateSelected: (count: number) => `${count} selected`,
    migrateConfirm: "Migrate selected",
    migrating: "Migrating",
    migrateCancel: "Cancel",
    migrateClose: "Close",
    migrateLoading: "Looking for skills",
    migrateDone: (count: number) => `Migrated ${count} ${count === 1 ? "skill" : "skills"}`,
    migrateNone: "No skills were migrated",
    migrateSkip: {
      "not-found": "This skill could not be found",
      unsafe: "This skill is outside the folders that can be migrated",
      "already-local": "Already in Vela’s skills folder",
      duplicate: "Skipped because another selected skill uses the same folder",
      failed: "Could not copy this skill",
    },
    autosaveNote: "Saved automatically when you stop typing or leave the field.",
    saving: "Saving",
    saved: "Saved",
    loadError: "Could not load agent settings",
  },
  models: {
    connected: "Connected providers",
    empty: "No providers yet. Add a custom model below.",
    connectedStatus: "Connected",
    disconnectedStatus: "Not connected",
    modelCount: (count: number) => `${count} available ${count === 1 ? "model" : "models"}`,
    visibility: "Models in the composer",
    visibilityHint: "Uncheck a model to keep it out of the model list in the home composer. You can check it again at any time. The model currently in use still appears so you can switch away.",
    visibilityEmpty: "No models are available yet. Sign in to a provider or add a model, then choose which ones to show.",
    visibilityHidden: "Hidden",
    visibilityShow: "Show in the composer",
    visibilityHide: "Hide from the composer",
    visibilityShowAll: (count: number) => `Show all (${count} hidden)`,
    login: "Log in",
    apiKey: "Enter API key",
    logout: "Log out",
    remove: "Remove",
    confirmRemove: "Confirm remove",
    add: "Add a custom model",
    providerName: "Provider name",
    providerPlaceholder: "For example, Ollama",
    baseUrl: "Endpoint",
    baseUrlPlaceholder: "http://127.0.0.1:11434/v1",
    api: "API type",
    apiKeyField: "API key",
    apiKeyPlaceholder: "Leave blank if this endpoint already has a key",
    modelId: "Model ID",
    modelIdPlaceholder: "qwen2.5-coder:7b",
    displayName: "Display name",
    displayNamePlaceholder: "Name shown in the model list",
    optional: "Optional",
    reasoning: "Supports reasoning",
    context: "Context length",
    maxOutput: "Max output length",
    optionalPlaceholder: "Optional",
    submit: "Test and add model",
    submitting: "Testing",
    added: "Added",
    keyHint: "The API key stays on this Mac and is used to reach that provider.",
    providerInvalid: "Enter a provider name.",
    apis: {
      "openai-completions": "OpenAI Chat Completions",
      "openai-responses": "OpenAI Responses",
      "anthropic-messages": "Anthropic Messages",
      "google-generative-ai": "Google Generative AI",
    },
  },
  permissions: {
    title: "Execution permissions",
    ask: "Ask every time",
    askHint: "Each terminal command needs your approval. Changes outside the workspace also need approval; edits inside the workspace do not.",
    smart: "Smart approval",
    smartHint: "The model selected for the current conversation checks each action first. Only risky actions, or when the check fails, need your approval; low-risk actions run directly.",
    full: "Full access",
    fullHint: "Run commands and edit files within the current tool permissions without asking each time.",
    note: "Execution permissions change what the agent can do on its own. You can switch them beside the input at any time.",
  },
  workspace: {
    current: "Current workspace",
    empty: "No workspace selected",
    choose: "Choose folder",
    close: "Close workspace",
    recent: "Recent",
    recentEmpty: "No recent folders yet.",
    removeRecent: "Remove from recent",
    environment: "Execution environment",
    local: "Local",
    localHint: "Work directly in the current workspace.",
    worktree: "Worktree",
    worktreeHint: "Use a separate Git worktree, so code changes stay isolated.",
    sandbox: "Sandbox",
    remote: "Remote",
    soon: "Coming soon",
    switching: "Switching",
  },
  appearance: {
    theme: "Color mode",
    system: "System",
    light: "Light",
    dark: "Dark",
    palette: "Theme",
    paletteHint: "Pick one light and one dark theme. With System, Vela switches between them as your OS appearance changes.",
    lightThemes: "Light themes",
    darkThemes: "Dark themes",
    inUse: "In use",
    themes: {
      daylight: { name: "Daylight", hint: "Crisp white with clear blue" },
      paper: { name: "Paper", hint: "Warm cream with terracotta" },
      celadon: { name: "Celadon", hint: "Pale jade glaze with teal" },
      midnight: { name: "Midnight", hint: "Deep navy for calm focus" },
      graphite: { name: "Graphite", hint: "Neutral near-black with lavender" },
      ember: { name: "Ember", hint: "Warm charcoal with glowing orange" },
    },
    language: "Language",
    soundEffects: "Task sounds",
    soundEffectsHint: "Play a short cue for errors, completion, questions, and permission requests, including background chats.",
    soundEffectsOn: "On",
    soundEffectsOff: "Off",
    soundPreview: "Preview sounds",
    soundError: "Error",
    soundComplete: "Complete",
    soundQuestion: "Question",
    soundPermission: "Permission",
    zh: "简体中文",
    en: "English",
    infoLayout: "Information layout",
    infoLayoutHint: "Use a fixed translucent sidebar, or float the environment card above the conversation and click the context ring below the composer for usage details.",
    infoLayoutSidebar: "Translucent sidebar",
    infoLayoutFloating: "Floating information",
    conversationLinkTarget: "Conversation links",
    conversationLinkHint: "Open web links clicked in conversations in a new browser tab on the right, or in your default system browser.",
    linkEmbedded: "Built-in browser",
    linkExternal: "System browser",
    sidebarItems: "Sidebar tabs",
    sidebarItemsHint: "Choose which shortcuts appear at the top of the left sidebar.",
    sidebarItemLabels: { prInbox: "Pull Requests", scheduledTasks: "Scheduled Tasks", newChat: "New chat", recipes: "Task Recipes" },
    composerCapsules: "Composer option backgrounds",
    composerCapsulesHint: "Show capsule backgrounds for attachments, chat mode, permissions, reasoning effort, and model controls.",
    composerCapsulesOff: "Off",
    composerCapsulesOn: "On",
    sendButtonIcon: "Send button icon",
    sendButtonIconPaperPlane: "Paper plane",
    sendButtonIconArrowUp: "Up arrow",
    toolDisplay: "Tool call display",
    toolDisplayHint: "“Cards” show one expandable card per tool call. “Compact” shows one line per tool, collapsing into a summary after multiple calls; click a file name to preview it on the right.",
    toolCard: "Cards",
    toolCompact: "Compact",
    toolFold: "Tool grouping",
    toolFoldHint: "“By assistant message” merges consecutive calls inside one message. “By position” also merges calls from adjacent messages; thinking, visible text, user messages, and interactive cards still break the grouping.",
    toolFoldMessage: "By assistant message",
    toolFoldPosition: "By position",
    toolProcessDetails: "Process durations & fold memory",
    toolProcessDetailsHint: "Show per-call and per-turn durations on compact process rows, and remember expanded or collapsed rows across restarts. Durations come from the existing trace, so chats without recorded timing stay unlabeled.",
    toolProcessDetailsOff: "Off",
    toolProcessDetailsOn: "On",
    thinkingSummary: "Thinking summaries",
    thinkingSummaryHint: "Automatically summarize newly completed thinking in your interface language. Past thinking can be summarized manually. Each summary makes an additional model request.",
    thinkingSummaryOff: "Off",
    thinkingSummaryOn: "Automatic",
    thinkingSummaryModel: "Thinking summary model",
    thinkingSummaryModelHint: "Follow the current chat by default, or choose a separate model for automatic and manual summaries. Changes apply to new summaries; existing summaries are kept.",
    thinkingSummaryModelCurrent: "Follow current chat model",
    thinkingSummaryModelConfigure: "Add a custom model in Models & accounts to make it available here.",
    thinkingSummaryModelUnavailable: "Unavailable",
    thinkingSummaryModelMissing: "The selected model is unavailable. Configure it again in Models & accounts, or choose another model.",
    thinkingSummaryStyle: "Summary display",
    thinkingSummaryStyleHint: "“After Thinking” keeps one summary line next to the Thinking label. “As heading” turns the summary into the trigger and expands the full summary and thinking below. “Like reply” renders the summary as reply text, with an expand icon at the end of the last line for the thinking content.",
    thinkingSummaryStyleInline: "After Thinking",
    thinkingSummaryStyleHeadline: "As heading",
    thinkingSummaryStyleProse: "Like reply",
    fileIconTheme: "File icons",
    fileIconThemeHint: "Choose the icon style used in file previews and tool calls.",
    devicon: "Devicon",
    materialIconTheme: "Material Icon Theme",
    shortcuts: "Shortcuts",
    shortcutsHint: "These shortcuts work today.",
    items: {
      sidebar: "Toggle sidebar",
      panel: "Toggle the right panel",
      settings: "Open settings",
      search: "Search settings (while in Settings)",
      close: "Close settings or dialog",
      send: "Send message",
      newline: "New line",
    },
  },
};

export type SettingsCopy = typeof zh;

export function settingsCopy(locale: AppLocale): SettingsCopy {
  return localizeCopy(locale, zh, en);
}
