packages:
  - "apps/*"
  - "packages/*"

nodeLinker: hoisted
confirmModulesPurge: false

allowBuilds:
  electron: true
  esbuild: true
  protobufjs: false
  "@google/genai": false
  electron-winstaller: false
  node-pty: true
